---
week: "08"
title: "W#08"
---

##  Linear Model: Categorical Predictors, More Predictors, Interaction; Categorical Response, Logistic Regression {.unnumbered}

Reconsider the Lecture Material, consider the Additional Readings and Material, and check the Achievements for yourself. Work on the Homework Projects reach out for help if you get stuck.

## Lecture Material

Slides: [Direct Link](../lectures/W{{< meta week >}}.qmd)

```{=html}
<iframe src="https://{{< var org.name >}}.github.io/Website/lectures/W{{< meta week >}}.html" frameborder="0" width="800" height="550" style="border:1px solid black;" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
```

## Additional Readings and Material  

Read the following section in [Introduction to Modern Statistics](https://openintro-ims.netlify.app/):


- [Ch 8: Linear regression with multiple predictors](https://openintro-ims.netlify.app/model-mlr)
- [Ch 9: Logistic Regression](https://openintro-ims.netlify.app/model-logistic)


## Achievements

You 

- [ ] know how to interpret the $R^2$ of a linear model
- [ ] know what dummy variables are and how many you need for a categorical variable with $k$ levels
- [ ] can interpret the coefficients of a linear model with dummy variables as main effects, in particular you 
    - [ ] know what it means that the intercept is the mean of the reference category (the one which is not represented by a dummy variable)
    - [ ] know that the coefficient of a dummy variable is the difference of the mean of the category represented by the dummy variable and the mean of the reference category
- [ ] can interpret the coefficients of interaction effects of dummy variables with a numerical variable
- [ ] know how to compute the odds and the log-odds of a probability and the other way round and how the range of theoretically possible values changes between the three ways to represent the same information
- [ ] can visually sketch the logistic and the logit function within their ranges on the x-axis and y-axis
- [ ] can explain the goal of logistic regression and the conceptual steps such that a linear model can be used


## Homework Projects Progress Guides

Find the Repositories of your Homework Projects in the Course's GitHub-Organization's [{{< var org.name >}} > Repositories](https://github.com/orgs/{{< var org.name >}}/repositories).

Project's INSTRUCTIONS you should have completed:   

**Project_NYCFlights**: 1., 2., 3., 4. 5., 6., 7.    
**Project_COVID19**: 1.1, 1.2, 1.3, 1.4, 1.5, 2.1, 2.2    
**Project_DataScienceProfiles**: **1., 2., 3. (Basics); 4. (Data Audit), 5. (PCA), 6. (Linear/Logistic Models)**   
**Project_FuelWatch**: **1., 2., 3., 4.** 

::: {.callout-note}
Don't panic, if you fell behind, just do it later. Find your own learning path. Better step by step than randomly skipping things. It is about learning not just completing!
:::