---
week: "09"
title: "W#09"
---

## Prediction (Building a Spam Filter), Classification and Regression with Decision Trees {.unnumbered}

Reconsider the Lecture Material, check the Achievements for yourself. Work on the Homework Projects.

## Lecture Material

Slides: [Direct Link](../lectures/W{{< meta week >}}.qmd)

```{=html}
<iframe src="https://{{< var org.name >}}.github.io/Website/lectures/W{{< meta week >}}.html" frameborder="0" width="800" height="550" style="border:1px solid black;" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
```

Find the live recording in the [Course's Team's Recording Folder]({{< var teams.concepts.recording_folder_link >}}). 


## Achievements
 
You

- [ ] can distinguish the goals and mindsets of prediction and explanation and how a logistic regression or a linear model can be used for both
- [ ] know how a threshold probability can be used to make a classifier for actual binary predictions (yes or no) from the predicted log-odds of a logistic regression (which can be transformed to odds or probabilities)
- [ ] know what the four basic values of the confusion matrix of a classifier are (TP, FN, FP, TN)
- [ ] can make sense of the various derived measures of a classifier like accuracy, sensitivity, specificity, precision, recall (you are not expected to memorize the exact definition you can look them up)
- [ ] can explain why data is split into training and testing data and how this relates to the goals of prediction (but not to explanation)
- [ ] can explain how a classifier can manage the trade-off between sensitivity and specificity from the ROC-curve (by changing the threshold probability) 
- [ ] can explain what the AUC of a ROC-curve is
- [ ] can explain how a decision tree can make predictions in a classification problem
- [ ] can explain how a decision tree can make predictions in a regression problem
- [ ] you know what can be called a "model" and how this can mean things in different "granularity"
- [ ] can explain and interpret the performance measures for regression problems: 
    - [ ] root mean squared error (RMSE), you also know why the square root is taken
    - [ ] R-squared


## Homework Projects Progress Guides

Find the Repositories of your Homework Projects in the Course's GitHub-Organization's [{{< var org.name >}} > Repositories](https://github.com/orgs/{{< var org.name >}}/repositories).

Project's INSTRUCTIONS you should have completed:   

**Project_NYCFlights**: 1., 2., 3., 4. 5., 6., 7.    
**Project_COVID19**: 1.1, 1.2, 1.3, 1.4, 1.5, 2.1, 2.2    
**Project_DataScienceProfiles**: 1., 2., 3., 4., 5., 6.     
**Project_FuelWatch**: 1., 2., 3., 4.

::: {.callout-note}
Don't panic, if you fell behind, just do it later. Find your own learning path. Better step by step than randomly skipping things. It is about learning not just completing!
:::