---
week: "10"
title: "W#10"
---

## Overfitting, Clustering Algorithms {.unnumbered}

Reconsider the Lecture Material, consider the Additional Readings and Material, and check the Achievements for yourself. Work on the Homework Projects reach out for help if you get stuck.

## Lecture Material

Slides: [Direct Link](../lectures/W{{< meta week >}}.qmd)

```{=html}
<iframe src="https://{{< var org.name >}}.github.io/Website/lectures/W{{< meta week >}}.html" frameborder="0" width="800" height="550" style="border:1px solid black;" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
```

Find the live recording in the [Course's Team's Recording Folder]({{< var teams.concepts.recording_folder_link >}}). 

## Additional Readings and Material  

Read sections of your interest in [Tidy Modeling with R](https://www.tmwr.org/). For example ab *Modeling Basics* and *Model Tuning*. 



## Achievements
 
You

- [ ] can explain the basic idea of the decision tree algorithm
- [ ] can explain the phenomenon of overfitting and why it is hard to assess
- [ ] know what a hyperparameter is in the context of statistical learning models
- [ ] can use list columns and the map function familiy to execute a performance systematic analysis
- [ ] can explain the difference between a regression, classification, and clustering problem
- [ ] can distinguish if statistical learning algorithm is supervised or unsupervised
- [ ] you can describe two algorithms of cluster analysis:
    - [ ] k-means
    - [ ] hierarchical clustering
- [ ] you know why k-means can results in different clusterings when run multiple times
- [ ] you now how to extract the cluster assignments for a ecertain number of clusters from a dendrogram of a hierarchical clustering

## Homework Projects Progress Guides

Find the Repositories of your Homework Projects in the Course's GitHub-Organization's [{{< var org.name >}} > Repositories](https://github.com/orgs/{{< var org.name >}}/repositories).

Project's INSTRUCTIONS you should have completed:   

**Project_NYCFlights**: 1., 2., 3., 4. 5., 6., 7.    
**Project_COVID19**: 1.1, 1.2, 1.3, 1.4, 1.5, 2.1, 2.2    
**Project_DataScienceProfiles**: 1., 2., 3., 4., 5., 6.     
**Project_FuelWatch**: 1., 2., 3., 4., **5. (Cluster analysis), 6.**

