---
week: "11"
title: "W#11"
---

## Collaborative Git, More Prediction Modeling, Quantifying Uncertainty, Crowd Wisdom {.unnumbered}

Reconsider the Lecture Material, consider the Additional Readings and Material, and check the Achievements for yourself. Work on the Homework Projects reach out for help if you get stuck.

## Lecture Material

Slides: [Direct Link](../lectures/W{{< meta week >}}.qmd)

```{=html}
<iframe src="https://{{< var org.name >}}.github.io/Website/lectures/W{{< meta week >}}.html" frameborder="0" width="800" height="550" style="border:1px solid black;" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
```

Find the live recording in the [Course's Team's Recording Folder]({{< var teams.concepts.recording_folder_link >}}). 

## Additional Readings and Material  

To come. 


## Achievements
 
You

- [ ] have successfully worked on a collaborative Git where you pull commits from colleagues, scrutinized how the new content was merged into you local work, and pushed your own commits 
- [ ] can explain cross-validation and a use case of it
- [ ] can explain the idea of tuning hyper-parameters in prediction models
- [ ] can explain how the random forest algorithm works and how it extends the idea of decision trees
- [ ] you now about the idea of variable importance for more complex machine learning models like random forests, and why such postmethods are not 
- [ ] can explain the idea and process of bootstrapping to quantify the uncertainty of a statistic
- [ ] know the difference between standard error and standard deviation
- [ ] can interpret what 95% confidence interval means (also for other confidence levels than 95%)
- [ ] can explain the relation of bias, variance, and MSE in the context of computing "crowd wisdom" estimates

## Homework Projects Progress Guides

Find the Repositories of your Homework Projects in the Course's GitHub-Organization's [{{< var org.name >}} > Repositories](https://github.com/orgs/{{< var org.name >}}/repositories).

Project's INSTRUCTIONS you should have completed:   

**Project_NYCFlights**: 1., 2., 3., 4. 5., 6., 7.    
**Project_COVID19**: 1.1, 1.2, 1.3, 1.4, 1.5, 2.1, 2.2    
**Project_DataScienceProfiles**: 1., 2., 3., 4., 5., 6.     
**Project_FuelWatch**: 1., 2., 3., 4., 5., 6.