<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jan Lorenz">

<title>W#07: Models in Science, Linear Model, Nonlinear Models – Data Science Concepts / Data Science Tools</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-16b4b51782fe9067b751a2cdf7d3de3a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed slimcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Data Science Concepts / Data Science Tools</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../index.html" aria-current="page"> 
<span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../schedule.html"> 
<span class="menu-text">Schedule</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/CU-F25-MDSSB-01-Concepts-Tools"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text">CU-F25-MDSSB-01-Concepts-Tools</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">W#07: Models in Science, Linear Model, Nonlinear Models</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
  <div id="quarto-announcement" data-announcement-id="0f8f92da8bb6fd80db00a7a45d195a06" class="alert alert-warning hidden"><i class="bi bi-info-circle quarto-announcement-icon"></i><div class="quarto-announcement-content">
<p><a href="https://forms.office.com/e/75qEdyZbim"><strong>Data Science Tools Final Project Check-In</strong></a> open! Deadline Sat, Nov 8.</p>
</div><i class="bi bi-x-lg quarto-announcement-action"></i></div>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Syllabus</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../schedule.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Schedule</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../material/M01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">W#01</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../material/M02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">W#02</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../material/M03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">W#03</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../material/M04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">W#04</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../material/M05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">W#05</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../material/M06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">W#06</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../material/M07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">W#07</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../material/M08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">W#08</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../material/M09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">W#09</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../material/M10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">W#10</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../material/M11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">W#11</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../material/M12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">W#12</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Checklist Technical Setup</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../literature.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Learning Resources</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../homework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Homework Projects</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../final.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Final Project</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../help.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Need help for Homework?</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#preliminaries" id="toc-preliminaries" class="nav-link active" data-scroll-target="#preliminaries"><span class="header-section-number">0.1</span> Preliminaries</a></li>
  <li><a href="#models-in-science" id="toc-models-in-science" class="nav-link" data-scroll-target="#models-in-science"><span class="header-section-number">1</span> Models in Science</a>
  <ul class="collapse">
  <li><a href="#what-is-a-model" id="toc-what-is-a-model" class="nav-link" data-scroll-target="#what-is-a-model"><span class="header-section-number">1.1</span> What is a model?</a></li>
  <li><a href="#scientific-modeling" id="toc-scientific-modeling" class="nav-link" data-scroll-target="#scientific-modeling"><span class="header-section-number">1.2</span> Scientific Modeling</a></li>
  <li><a href="#model-purposes-and-data-analysis" id="toc-model-purposes-and-data-analysis" class="nav-link" data-scroll-target="#model-purposes-and-data-analysis"><span class="header-section-number">1.3</span> Model Purposes and Data Analysis</a></li>
  <li><a href="#models-to-learn-from-data" id="toc-models-to-learn-from-data" class="nav-link" data-scroll-target="#models-to-learn-from-data"><span class="header-section-number">1.4</span> Models to Learn from Data</a></li>
  <li><a href="#modeling-mindsets" id="toc-modeling-mindsets" class="nav-link" data-scroll-target="#modeling-mindsets"><span class="header-section-number">1.5</span> Modeling Mindsets</a></li>
  <li><a href="#modeling-mindsets-1" id="toc-modeling-mindsets-1" class="nav-link" data-scroll-target="#modeling-mindsets-1"><span class="header-section-number">1.6</span> Modeling Mindsets</a></li>
  </ul></li>
  <li><a href="#linear-model" id="toc-linear-model" class="nav-link" data-scroll-target="#linear-model"><span class="header-section-number">2</span> Linear Model</a>
  <ul class="collapse">
  <li><a href="#hello-again-penguins" id="toc-hello-again-penguins" class="nav-link" data-scroll-target="#hello-again-penguins"><span class="header-section-number">2.1</span> Hello again penguins!</a></li>
  <li><a href="#body-mass-in-grams" id="toc-body-mass-in-grams" class="nav-link" data-scroll-target="#body-mass-in-grams"><span class="header-section-number">2.2</span> Body mass in grams</a></li>
  <li><a href="#flipper-length-in-millimeters" id="toc-flipper-length-in-millimeters" class="nav-link" data-scroll-target="#flipper-length-in-millimeters"><span class="header-section-number">2.3</span> Flipper length in millimeters</a></li>
  <li><a href="#model-linear-relation-of-variables" id="toc-model-linear-relation-of-variables" class="nav-link" data-scroll-target="#model-linear-relation-of-variables"><span class="header-section-number">2.4</span> Model: Linear relation of variables</a></li>
  <li><a href="#penguins-linear-model" id="toc-penguins-linear-model" class="nav-link" data-scroll-target="#penguins-linear-model"><span class="header-section-number">2.5</span> Penguins: Linear model</a></li>
  <li><a href="#penguins-a-smooth-curve" id="toc-penguins-a-smooth-curve" class="nav-link" data-scroll-target="#penguins-a-smooth-curve"><span class="header-section-number">2.6</span> Penguins: A smooth curve</a></li>
  <li><a href="#terminology-variable-based-models" id="toc-terminology-variable-based-models" class="nav-link" data-scroll-target="#terminology-variable-based-models"><span class="header-section-number">2.7</span> Terminology variable-based models</a></li>
  <li><a href="#more-explanatory-variables" id="toc-more-explanatory-variables" class="nav-link" data-scroll-target="#more-explanatory-variables"><span class="header-section-number">2.8</span> More explanatory variables</a></li>
  <li><a href="#ggplot-hint-how-to-color-penguins-but-keep-one-model" id="toc-ggplot-hint-how-to-color-penguins-but-keep-one-model" class="nav-link" data-scroll-target="#ggplot-hint-how-to-color-penguins-but-keep-one-model"><span class="header-section-number">2.9</span> ggplot-hint: How to color penguins but keep one model?</a></li>
  <li><a href="#beware-of-simpsons-paradox" id="toc-beware-of-simpsons-paradox" class="nav-link" data-scroll-target="#beware-of-simpsons-paradox"><span class="header-section-number">2.10</span> Beware of Simpson’s paradox</a></li>
  <li><a href="#the-paradox-is-real" id="toc-the-paradox-is-real" class="nav-link" data-scroll-target="#the-paradox-is-real"><span class="header-section-number">2.11</span> The paradox is real!</a></li>
  <li><a href="#models---upsides-and-downsides" id="toc-models---upsides-and-downsides" class="nav-link" data-scroll-target="#models---upsides-and-downsides"><span class="header-section-number">2.12</span> Models - upsides and downsides</a></li>
  <li><a href="#variation-around-a-model" id="toc-variation-around-a-model" class="nav-link" data-scroll-target="#variation-around-a-model"><span class="header-section-number">2.13</span> Variation around a model</a></li>
  <li><a href="#all-models-are-wrong" id="toc-all-models-are-wrong" class="nav-link" data-scroll-target="#all-models-are-wrong"><span class="header-section-number">2.14</span> <em>All models are wrong …</em></a></li>
  <li><a href="#two-model-purposes" id="toc-two-model-purposes" class="nav-link" data-scroll-target="#two-model-purposes"><span class="header-section-number">2.15</span> Two model purposes</a></li>
  </ul></li>
  <li><a href="#fitting-models" id="toc-fitting-models" class="nav-link" data-scroll-target="#fitting-models"><span class="header-section-number">3</span> Fitting Models</a>
  <ul class="collapse">
  <li><a href="#in-r-tidymodels" id="toc-in-r-tidymodels" class="nav-link" data-scroll-target="#in-r-tidymodels"><span class="header-section-number">3.1</span> In R: <code>tidymodels</code></a></li>
  <li><a href="#our-goal" id="toc-our-goal" class="nav-link" data-scroll-target="#our-goal"><span class="header-section-number">3.2</span> Our goal</a></li>
  <li><a href="#step-1-specify-model" id="toc-step-1-specify-model" class="nav-link" data-scroll-target="#step-1-specify-model"><span class="header-section-number">3.3</span> Step 1: Specify model</a></li>
  <li><a href="#step-2-set-the-model-fitting-engine" id="toc-step-2-set-the-model-fitting-engine" class="nav-link" data-scroll-target="#step-2-set-the-model-fitting-engine"><span class="header-section-number">3.4</span> Step 2: Set the model fitting <em>engine</em></a></li>
  <li><a href="#step-3-fit-model-and-estimate-parameters" id="toc-step-3-fit-model-and-estimate-parameters" class="nav-link" data-scroll-target="#step-3-fit-model-and-estimate-parameters"><span class="header-section-number">3.5</span> Step 3: Fit model and estimate parameters</a></li>
  <li><a href="#what-does-the-output-say" id="toc-what-does-the-output-say" class="nav-link" data-scroll-target="#what-does-the-output-say"><span class="header-section-number">3.6</span> What does the output say?</a></li>
  <li><a href="#show-output-in-tidy-form" id="toc-show-output-in-tidy-form" class="nav-link" data-scroll-target="#show-output-in-tidy-form"><span class="header-section-number">3.7</span> Show output in <em>tidy</em> form</a></li>
  <li><a href="#parameter-estimation" id="toc-parameter-estimation" class="nav-link" data-scroll-target="#parameter-estimation"><span class="header-section-number">3.8</span> Parameter estimation</a></li>
  <li><a href="#parsnip-model-objects" id="toc-parsnip-model-objects" class="nav-link" data-scroll-target="#parsnip-model-objects"><span class="header-section-number">3.9</span> <code>parsnip</code> model objects</a></li>
  <li><a href="#fit-is-the-object-created-by-lm-base-r" id="toc-fit-is-the-object-created-by-lm-base-r" class="nav-link" data-scroll-target="#fit-is-the-object-created-by-lm-base-r"><span class="header-section-number">3.10</span> <code>$fit</code> is the object created by <code>lm</code> (base R)</a></li>
  <li><a href="#fitting-method-least-squares-regression" id="toc-fitting-method-least-squares-regression" class="nav-link" data-scroll-target="#fitting-method-least-squares-regression"><span class="header-section-number">3.11</span> Fitting method: Least squares regression</a></li>
  <li><a href="#visualization-of-residuals" id="toc-visualization-of-residuals" class="nav-link" data-scroll-target="#visualization-of-residuals"><span class="header-section-number">3.12</span> Visualization of residuals</a></li>
  <li><a href="#check-fitted-values-and-residuals" id="toc-check-fitted-values-and-residuals" class="nav-link" data-scroll-target="#check-fitted-values-and-residuals"><span class="header-section-number">3.13</span> Check: Fitted values and Residuals</a></li>
  </ul></li>
  <li><a href="#nonlinear-models" id="toc-nonlinear-models" class="nav-link" data-scroll-target="#nonlinear-models"><span class="header-section-number">4</span> Nonlinear Models</a>
  <ul class="collapse">
  <li><a href="#when-a-linear-model-is-bad" id="toc-when-a-linear-model-is-bad" class="nav-link" data-scroll-target="#when-a-linear-model-is-bad"><span class="header-section-number">4.1</span> When a linear model is bad</a></li>
  <li><a href="#log-transformation" id="toc-log-transformation" class="nav-link" data-scroll-target="#log-transformation"><span class="header-section-number">4.2</span> <span class="math inline">\(\log\)</span> transformation</a></li>
  <li><a href="#exponential-growth" id="toc-exponential-growth" class="nav-link" data-scroll-target="#exponential-growth"><span class="header-section-number">4.3</span> Exponential growth!</a></li>
  <li><a href="#log-transformation-1" id="toc-log-transformation-1" class="nav-link" data-scroll-target="#log-transformation-1"><span class="header-section-number">4.4</span> <span class="math inline">\(\log\)</span> transformation</a></li>
  <li><a href="#however-it-works-only-in-a-certain-range" id="toc-however-it-works-only-in-a-certain-range" class="nav-link" data-scroll-target="#however-it-works-only-in-a-certain-range"><span class="header-section-number">4.5</span> However, it works only in a certain range</a></li>
  <li><a href="#however-it-works-only-in-a-certain-range-log-scale-on-y" id="toc-however-it-works-only-in-a-certain-range-log-scale-on-y" class="nav-link" data-scroll-target="#however-it-works-only-in-a-certain-range-log-scale-on-y"><span class="header-section-number">4.6</span> However, it works only in a certain range (log scale on y)</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="W07.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">W#07: Models in Science, Linear Model, Nonlinear Models</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jan Lorenz </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="preliminaries" class="level2" data-number="0.1">
<h2 data-number="0.1" class="anchored" data-anchor-id="preliminaries"><span class="header-section-number">0.1</span> Preliminaries</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.1     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.3     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ────────────────────────────────────── tidymodels 1.5.0 ──
✔ broom        1.0.13     ✔ rsample      1.3.2 
✔ dials        1.4.4      ✔ tailor       0.1.0 
✔ infer        1.1.0      ✔ tune         2.1.0 
✔ modeldata    1.5.1      ✔ workflows    1.3.0 
✔ parsnip      1.6.0      ✔ workflowsets 1.1.1 
✔ recipes      1.3.3      ✔ yardstick    1.4.0 
── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
✖ scales::discard() masks purrr::discard()
✖ dplyr::filter()   masks stats::filter()
✖ recipes::fixed()  masks stringr::fixed()
✖ dplyr::lag()      masks stats::lag()
✖ yardstick::spec() masks readr::spec()
✖ recipes::step()   masks stats::step()</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(palmerpenguins)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'palmerpenguins'

The following object is masked from 'package:modeldata':

    penguins

The following objects are masked from 'package:datasets':

    penguins, penguins_raw</code></pre>
</div>
</div>
</section>
<section id="models-in-science" class="level1 page-columns page-full" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Models in Science</h1>
<section id="what-is-a-model" class="level2 smaller page-columns page-full" data-background-color="khaki" data-number="1.1">
<h2 class="smaller anchored" data-background-color="khaki" data-number="1.1" data-anchor-id="what-is-a-model"><span class="header-section-number">1.1</span> What is a model?</h2>
<ul>
<li>A model is an informative representation of an object, person or system.</li>
</ul>
<p><img src="https://upload.wikimedia.org/wikipedia/commons/4/46/Astrid_Andersen_01.jpg" height="200"> <img src="https://upload.wikimedia.org/wikipedia/commons/b/b8/Beta-D-Gulopyranose_Molek%C3%BClbaukasten_9288.JPG" height="200"> <img src="https://upload.wikimedia.org/wikipedia/commons/7/73/AtmosphericModelSchematic.png" height="200"></p>
<ul>
<li>A model is a <span style="color:blue;"><strong>simplified</strong></span> representation of the real world focusing on the essential parts for its <span style="color:blue;"><strong>purpose</strong></span>.</li>
</ul>

<div class="no-row-height column-margin column-container"><div class="margin-aside">
<p>Source: <a href="https://en.wikipedia.org/wiki/Model" class="uri">https://en.wikipedia.org/wiki/Model</a></p>
</div></div></section>
<section id="scientific-modeling" class="level2 smaller page-columns page-full" data-background-color="khaki" data-number="1.2">
<h2 class="smaller anchored" data-background-color="khaki" data-number="1.2" data-anchor-id="scientific-modeling"><span class="header-section-number">1.2</span> Scientific Modeling</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Scientific modeling</strong> is an activity that produces models representing empirical objects, phenomena, and physical processes, to make a particular part or feature of the world easier to</p>
<ul>
<li>understand,</li>
<li>define,</li>
<li>quantify,</li>
<li>visualize, or</li>
<li>simulate.</li>
</ul>
</div><div class="column" style="width:50%;">
<p><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/MathModel.svg/2560px-MathModel.svg.png" class="img-fluid"></p>
<section id="famous-wisdom" class="level4" data-number="1.2.0.1">
<h4 data-number="1.2.0.1" class="anchored" data-anchor-id="famous-wisdom"><span class="header-section-number">1.2.0.1</span> Famous wisdom</h4>
<blockquote class="blockquote">
<p><a href="https://en.wikipedia.org/wiki/All_models_are_wrong">All models are wrong, but some are useful.</a></p>
</blockquote>
</section>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="margin-aside">
<p>Source: <a href="https://en.wikipedia.org/wiki/Scientific_modelling" class="uri">https://en.wikipedia.org/wiki/Scientific_modelling</a></p>
</div></div></section>
<section id="model-purposes-and-data-analysis" class="level2 smaller" data-background-color="khaki" data-number="1.3">
<h2 class="smaller anchored" data-background-color="khaki" data-number="1.3" data-anchor-id="model-purposes-and-data-analysis"><span class="header-section-number">1.3</span> Model Purposes and Data Analysis</h2>
<div class="columns">
<div class="column" style="width:60%;">
<ul>
<li><strong>Agent-based models</strong> and <strong>differential equations</strong>
<ul>
<li>are used to <strong>explain</strong> the <strong>dynamics</strong> of one or more variables (typically) over time. They are used to answer <span style="color:blue;"><em>mechanistic questions</em></span>.</li>
</ul></li>
<li><span style="color:blue;"><strong>Variable-based models</strong></span>
<ul>
<li>are used to specify relations between variables</li>
<li>to <strong>explain</strong> relations and make <strong>predictions</strong>.</li>
<li>Used to answer <span style="color:blue;"><em>inferential</em></span> and <span style="color:blue;"><em>predictive questions</em></span>.<br>
</li>
<li>(With experimental and theoretical effort also for <span style="color:blue;"><em>causal questions</em></span>.)</li>
</ul></li>
</ul>
</div><div class="column" style="width:40%;">
<p><img src="img/DataAnalysisFlowChart_LeekPeng.jpeg" class="img-fluid"></p>
</div>
</div>
<p>. . .</p>
<p>The most basic variable-based model is the <span style="color:blue;"><strong>linear model</strong></span>.</p>
</section>
<section id="models-to-learn-from-data" class="level2 smaller" data-background-color="khaki" data-number="1.4">
<h2 class="smaller anchored" data-background-color="khaki" data-number="1.4" data-anchor-id="models-to-learn-from-data"><span class="header-section-number">1.4</span> Models to Learn from Data</h2>
<p>In much of the following we use a <em>narrower</em> definition of <strong>model</strong>:</p>
<p>A <strong>mathematical model</strong> that consists of <strong>variables</strong> and <strong>functions</strong>.</p>
<div class="columns">
<div class="column" style="width:50%;">
<p>Different names and roles of <span style="color:blue;"><strong>variables</strong></span>:</p>
<ul>
<li>random variables</li>
<li>covariates</li>
<li>predictors</li>
<li>latent variables</li>
<li>features</li>
<li>targets</li>
<li>outcomes</li>
</ul>
</div><div class="column" style="width:50%;">
<p><span style="color:blue;"><strong>Functions</strong></span> relate variables to each other</p>
<ul>
<li>In a linear model we model one variable as a weighted sum of the other variables</li>
</ul>
<p>Once a model (setup of variables and functions) is specified, modelers use <span style="color:blue;"><strong>Data</strong></span> to find the <em>best</em> function, called</p>
<ul>
<li>estimation</li>
<li>training</li>
<li>fitting</li>
<li>learning</li>
</ul>
</div>
</div>
</section>
<section id="modeling-mindsets" class="level2 smaller page-columns page-full" data-background-color="khaki" data-number="1.5">
<h2 class="smaller anchored" data-background-color="khaki" data-number="1.5" data-anchor-id="modeling-mindsets"><span class="header-section-number">1.5</span> Modeling Mindsets</h2>
<p>Even within the setup of <em>Models to Learn from Data</em> there are many different <span style="color:blue;"><strong>Modeling Mindsets</strong></span></p>
<p><img src="img/ModelingMindsets.png" class="img-fluid"></p>

<div class="no-row-height column-margin column-container"><div class="margin-aside">
<p>Molnar, C. (2022). <a href="https://books.google.de/books?id=qV-DzwEACAAJ">Modeling mindsets: The many cultures of learning from data.</a> Christoph Molnar c/o Mucbook Clubhouse.</p>
</div></div></section>
<section id="modeling-mindsets-1" class="level2 smaller page-columns page-full" data-background-color="khaki" data-number="1.6">
<h2 class="smaller anchored" data-background-color="khaki" data-number="1.6" data-anchor-id="modeling-mindsets-1"><span class="header-section-number">1.6</span> Modeling Mindsets</h2>
<p>Even within the setup of <em>Models to Learn from Data</em> there are many different <span style="color:blue;"><strong>Modeling Mindsets</strong></span></p>
<p><img src="img/ModelingMindsets_annotated.png" class="img-fluid"></p>

<div class="no-row-height column-margin column-container"><div class="margin-aside">
<p>Molnar, C. (2022). <a href="https://books.google.de/books?id=qV-DzwEACAAJ">Modeling mindsets: The many cultures of learning from data.</a> Christoph Molnar c/o Mucbook Clubhouse.</p>
</div></div></section>
</section>
<section id="linear-model" class="level1 page-columns page-full" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Linear Model</h1>
<p>The first work-horse model in data science</p>
<section id="hello-again-penguins" class="level2 scrollable smaller" data-number="2.1">
<h2 class="scrollable smaller anchored" data-number="2.1" data-anchor-id="hello-again-penguins"><span class="header-section-number">2.1</span> Hello again penguins!</h2>
<p>We use the dataset <a href="https://allisonhorst.github.io/palmerpenguins/">Palmer Penguins</a></p>
<p>Chinstrap, Gentoo, and Adélie Penguins</p>
<p><img src="https://upload.wikimedia.org/wikipedia/commons/0/08/South_Shetland-2016-Deception_Island%E2%80%93Chinstrap_penguin_%28Pygoscelis_antarctica%29_04.jpg" height="200"> <img src="https://upload.wikimedia.org/wikipedia/commons/0/00/Brown_Bluff-2016-Tabarin_Peninsula%E2%80%93Gentoo_penguin_%28Pygoscelis_papua%29_03.jpg" height="200"> <img src="https://upload.wikimedia.org/wikipedia/commons/e/e3/Hope_Bay-2016-Trinity_Peninsula%E2%80%93Ad%C3%A9lie_penguin_%28Pygoscelis_adeliae%29_04.jpg" height="200"></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>penguins</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 344 × 8
   species island    bill_length_mm bill_depth_mm flipper_length_mm body_mass_g
   &lt;fct&gt;   &lt;fct&gt;              &lt;dbl&gt;         &lt;dbl&gt;             &lt;int&gt;       &lt;int&gt;
 1 Adelie  Torgersen           39.1          18.7               181        3750
 2 Adelie  Torgersen           39.5          17.4               186        3800
 3 Adelie  Torgersen           40.3          18                 195        3250
 4 Adelie  Torgersen           NA            NA                  NA          NA
 5 Adelie  Torgersen           36.7          19.3               193        3450
 6 Adelie  Torgersen           39.3          20.6               190        3650
 7 Adelie  Torgersen           38.9          17.8               181        3625
 8 Adelie  Torgersen           39.2          19.6               195        4675
 9 Adelie  Torgersen           34.1          18.1               193        3475
10 Adelie  Torgersen           42            20.2               190        4250
# ℹ 334 more rows
# ℹ 2 more variables: sex &lt;fct&gt;, year &lt;int&gt;</code></pre>
</div>
</div>
</section>
<section id="body-mass-in-grams" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="body-mass-in-grams"><span class="header-section-number">2.2</span> Body mass in grams</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>penguins <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(body_mass_g)) <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value `binwidth`.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing non-finite outside the scale range
(`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W07_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="flipper-length-in-millimeters" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="flipper-length-in-millimeters"><span class="header-section-number">2.3</span> Flipper length in millimeters</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>penguins <span class="sc">|&gt;</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(flipper_length_mm)) <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value `binwidth`.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing non-finite outside the scale range
(`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W07_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="model-linear-relation-of-variables" class="level2 smaller" data-background-color="aquamarine" data-number="2.4">
<h2 class="smaller anchored" data-background-color="aquamarine" data-number="2.4" data-anchor-id="model-linear-relation-of-variables"><span class="header-section-number">2.4</span> Model: Linear relation of variables</h2>
<p>A <strong>line</strong> is a shift-scale transformation of the identity function usually written in the form</p>
<p><span class="math display">\[f(x) = a\cdot x + b\]</span></p>
<p>where <span style="color:red;"><span class="math inline">\(a\)</span> is the <em>slope</em></span>, <span style="color:blue;"><span class="math inline">\(b\)</span> is the <em>intercept</em></span>.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<div class="cell" data-output-location="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fl">0.5</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>func <span class="ot">&lt;-</span> <span class="cf">function</span>(x) a <span class="sc">*</span> x <span class="sc">+</span> b</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_function</span>(<span class="at">fun =</span> func, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Set axis limits and make axis equal</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.5</span>, <span class="dv">2</span>)) <span class="sc">+</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">2</span>)) <span class="sc">+</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_fixed</span>() <span class="sc">+</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># intercept line:</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> <span class="fu">tibble</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>), <span class="at">y =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)),</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">mapping =</span> <span class="fu">aes</span>(x, y),</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"blue"</span>,</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">2</span></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>    <span class="co"># slope:</span></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> <span class="fu">tibble</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="fl">1.5</span>, <span class="fl">1.5</span>), <span class="at">y =</span> <span class="fu">c</span>(<span class="fl">1.25</span>, <span class="fl">1.75</span>)),</span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">mapping =</span> <span class="fu">aes</span>(x, y),</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"red"</span>,</span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">2</span></span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(</span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>    <span class="co"># x-interval of length one:</span></span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> <span class="fu">tibble</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">1.5</span>), <span class="at">y =</span> <span class="fu">c</span>(<span class="fl">1.25</span>, <span class="fl">1.25</span>)),</span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">mapping =</span> <span class="fu">aes</span>(x, y),</span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"gray"</span></span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>(<span class="at">base_size =</span> <span class="dv">24</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W07_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="penguins-linear-model" class="level2 smaller" data-number="2.5">
<h2 class="smaller anchored" data-number="2.5" data-anchor-id="penguins-linear-model"><span class="header-section-number">2.5</span> Penguins: Linear model</h2>
<p><strong>Flipper length</strong> as a function of <strong>body mass</strong>.</p>
<div class="cell" data-output-location="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>penguins <span class="sc">|&gt;</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> body_mass_g, <span class="at">y =</span> flipper_length_mm)) <span class="sc">+</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>(<span class="at">base_size =</span> <span class="dv">24</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W07_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="penguins-a-smooth-curve" class="level2 smaller" data-number="2.6">
<h2 class="smaller anchored" data-number="2.6" data-anchor-id="penguins-a-smooth-curve"><span class="header-section-number">2.6</span> Penguins: A smooth curve</h2>
<p><strong>Flipper length</strong> as a function of <strong>body mass</strong> with <code>loess</code><a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> smoothing.</p>
<div class="cell" data-output-location="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>penguins <span class="sc">|&gt;</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> body_mass_g, <span class="at">y =</span> flipper_length_mm)) <span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>) <span class="sc">+</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>(<span class="at">base_size =</span> <span class="dv">24</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W07_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This is a less theory-driven and more data-driven model. Why?<br>
<span class="fragment">We don’t have a simple mathematical form of the function.</span></p>
</section>
<section id="terminology-variable-based-models" class="level2 smaller" data-background-color="khaki" data-number="2.7">
<h2 class="smaller anchored" data-background-color="khaki" data-number="2.7" data-anchor-id="terminology-variable-based-models"><span class="header-section-number">2.7</span> Terminology variable-based models</h2>
<ul>
<li><strong>Response variable:</strong><a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> Variable whose behavior or variation you are trying to understand, on the y-axis</li>
<li><strong>Explanatory variable(s):</strong><a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> Other variable(s) that you want to use to explain the variation in the response, on the x-axis</li>
<li><strong>Predicted value:</strong> Output of the model function.
<ul>
<li>The model function gives the <strong>(expected) average value</strong> of the response variable conditioning on the explanatory variables</li>
<li><strong>Residual(s):</strong> A measure of how far away a case is from its predicted value (based on the particular model)<br>
Residual = Observed value minus Predicted value<br>
The residual tells how far above/below the expected value each case is</li>
</ul></li>
</ul>
</section>
<section id="more-explanatory-variables" class="level2 smaller" data-number="2.8">
<h2 class="smaller anchored" data-number="2.8" data-anchor-id="more-explanatory-variables"><span class="header-section-number">2.8</span> More explanatory variables</h2>
<p>How does the relation between flipper length and body mass change with different species?</p>
<div class="cell" data-output-location="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>penguins <span class="sc">|&gt;</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> body_mass_g, <span class="at">y =</span> flipper_length_mm, <span class="at">color =</span> species)) <span class="sc">+</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>(<span class="at">base_size =</span> <span class="dv">24</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W07_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="ggplot-hint-how-to-color-penguins-but-keep-one-model" class="level2 smaller" data-number="2.9">
<h2 class="smaller anchored" data-number="2.9" data-anchor-id="ggplot-hint-how-to-color-penguins-but-keep-one-model"><span class="header-section-number">2.9</span> ggplot-hint: How to color penguins but keep one model?</h2>
<p>Put the mapping of the color aesthetic into the <code>geom_point</code> command.</p>
<div class="cell" data-output-location="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>penguins <span class="sc">|&gt;</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> body_mass_g, <span class="at">y =</span> flipper_length_mm)) <span class="sc">+</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> species)) <span class="sc">+</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>(<span class="at">base_size =</span> <span class="dv">24</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W07_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="beware-of-simpsons-paradox" class="level2 smaller page-columns page-full" data-background-color="aquamarine" data-number="2.10">
<h2 class="smaller anchored" data-background-color="aquamarine" data-number="2.10" data-anchor-id="beware-of-simpsons-paradox"><span class="header-section-number">2.10</span> Beware of Simpson’s paradox</h2>
<p>Slopes for all groups can be in the opposite direction of the main effect’s slope!</p>
<p><img src="https://upload.wikimedia.org/wikipedia/commons/f/fb/Simpsons_paradox_-_animation.gif" height="400"></p>

<div class="no-row-height column-margin column-container"><div class="margin-aside">
<p>Source: <a href="https://en.wikipedia.org/wiki/Simpson%27s_paradox" class="uri">https://en.wikipedia.org/wiki/Simpson%27s_paradox</a></p>
</div></div></section>
<section id="the-paradox-is-real" class="level2 smaller" data-number="2.11">
<h2 class="smaller anchored" data-number="2.11" data-anchor-id="the-paradox-is-real"><span class="header-section-number">2.11</span> The paradox is real!</h2>
<p>How does the relation between bill length and body mass change with different species?</p>
<div class="cell" data-output-location="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>penguins <span class="sc">|&gt;</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> bill_length_mm, <span class="at">y =</span> bill_depth_mm)) <span class="sc">+</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> species)) <span class="sc">+</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">color =</span> species), <span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>(<span class="at">base_size =</span> <span class="dv">24</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W07_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="models---upsides-and-downsides" class="level2 smaller" data-background-color="khaki" data-number="2.12">
<h2 class="smaller anchored" data-background-color="khaki" data-number="2.12" data-anchor-id="models---upsides-and-downsides"><span class="header-section-number">2.12</span> Models - upsides and downsides</h2>
<ul>
<li>Models can reveal patterns that are not evident in a graph of the data. This is an advantage of modeling over simple visual inspection of data.
<ul>
<li>How would you visualize dependencies of more than two variables?</li>
</ul></li>
<li>The risk is that a model is imposing structure that is not really there in the real world data.
<ul>
<li>People imagined animal shapes in the stars. This is maybe a good model to detect and memorize shapes, but it has nothing to do with these animals.</li>
<li>Every model is a simplification of the real world, but there are good and bad models (for particular purposes).</li>
<li>A skeptical (but constructive) approach to a model is always advisable.</li>
</ul></li>
</ul>
</section>
<section id="variation-around-a-model" class="level2 smaller" data-background-color="khaki" data-number="2.13">
<h2 class="smaller anchored" data-background-color="khaki" data-number="2.13" data-anchor-id="variation-around-a-model"><span class="header-section-number">2.13</span> Variation around a model</h2>
<p>… is as interesting and important as the model!</p>
<p><em><span style="color:blue;"><strong>Statistics</strong></span> is the explanation of uncertainty of variation in the context of what remains unexplained.</em></p>
<ul>
<li>The scattered data of flipper length and body mass suggests that there maybe other factors that account for some parts of the variability.</li>
<li>Or is it randomness?</li>
<li>Adding more explanatory variables can help (but need not)</li>
</ul>
</section>
<section id="all-models-are-wrong" class="level2 smaller" data-background-color="khaki" data-number="2.14">
<h2 class="smaller anchored" data-background-color="khaki" data-number="2.14" data-anchor-id="all-models-are-wrong"><span class="header-section-number">2.14</span> <em>All models are wrong …</em></h2>
<p><em>… but some are useful.</em> (George Box)</p>
<p>Extending the range of the model:</p>
<div class="cell" data-output-location="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>penguins <span class="sc">|&gt;</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> body_mass_g, <span class="at">y =</span> flipper_length_mm)) <span class="sc">+</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">"lm"</span>,</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">se =</span> <span class="cn">FALSE</span>,</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">fullrange =</span> <span class="cn">TRUE</span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">7000</span>)) <span class="sc">+</span></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">230</span>)) <span class="sc">+</span></span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>(<span class="at">base_size =</span> <span class="dv">24</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 3 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 3 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 10 rows containing missing values or values outside the scale range
(`geom_smooth()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W07_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>The model predicts that penguins with zero weight still have flippers of about 140 mm on average.</li>
<li>Is the model useless? <span class="fragment">Yes, around zero body mass.<br>
However, it works OK in the range of the body mass data.</span></li>
</ul>
</section>
<section id="two-model-purposes" class="level2 smaller" data-background-color="khaki" data-number="2.15">
<h2 class="smaller anchored" data-background-color="khaki" data-number="2.15" data-anchor-id="two-model-purposes"><span class="header-section-number">2.15</span> Two model purposes</h2>
<p>Linear models can be used for:</p>
<ul>
<li><strong>Explanation:</strong> Understand the relationship of variables in a quantitative way.<br>
<em>For the linear model, interpret slope and intercept.</em>
<ul>
<li>In other words: We make <strong>inference</strong> about relations in any sample of penguins.</li>
<li>Warning: We use the word “explain” because it is an established statistical term for describing relations. However, <strong>beware a relation is not causation!</strong><br>
When discussing causation, much more is needed than a statistical relation.<br>
In substantive discussion about model output we speak about the not-necessarily causal <em>relation</em> or <em>association</em> of variables.<br>
</li>
</ul></li>
<li><strong>Prediction:</strong> Plug in new values for the explanatory variable(s) and receive the expected response value.<br>
<em>For the linear model, predict the flipper length of new penguins by their body mass.</em></li>
</ul>
</section>
</section>
<section id="fitting-models" class="level1 page-columns page-full" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Fitting Models</h1>
<p>Today: The linear model.</p>
<section id="in-r-tidymodels" class="level2 page-columns page-full" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="in-r-tidymodels"><span class="header-section-number">3.1</span> In R: <code>tidymodels</code></h2>
<p><img src="https://datasciencebox.org/course-materials/_slides/u4-d02-fitting-interpreting-models/img/tidymodels.png" class="img-fluid"></p>

<div class="no-row-height column-margin column-container"><div class="margin-aside">
<p>From <a href="https://datasciencebox.org" class="uri">https://datasciencebox.org</a></p>
</div></div></section>
<section id="our-goal" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="our-goal"><span class="header-section-number">3.2</span> Our goal</h2>
<p>Predict flipper length from body mass</p>
<p>average <code>flipper_length_mm</code> <span class="math inline">\(= \beta_0 + \beta_1\cdot\)</span> <code>body_mass_g</code></p>
</section>
<section id="step-1-specify-model" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="step-1-specify-model"><span class="header-section-number">3.3</span> Step 1: Specify model</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">linear_reg</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear Regression Model Specification (regression)

Computational engine: lm </code></pre>
</div>
</div>
</section>
<section id="step-2-set-the-model-fitting-engine" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="step-2-set-the-model-fitting-engine"><span class="header-section-number">3.4</span> Step 2: Set the model fitting <em>engine</em></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">linear_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear Regression Model Specification (regression)

Computational engine: lm </code></pre>
</div>
</div>
</section>
<section id="step-3-fit-model-and-estimate-parameters" class="level2 smaller page-columns page-full" data-number="3.5">
<h2 class="smaller anchored" data-number="3.5" data-anchor-id="step-3-fit-model-and-estimate-parameters"><span class="header-section-number">3.5</span> Step 3: Fit model and estimate parameters</h2>
<p>Only now, the data and the variable selection comes in.</p>
<p>Use of <strong>formula syntax</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">linear_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">|&gt;</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(flipper_length_mm <span class="sc">~</span> body_mass_g, <span class="at">data =</span> penguins)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>parsnip model object


Call:
stats::lm(formula = flipper_length_mm ~ body_mass_g, data = data)

Coefficients:
(Intercept)  body_mass_g  
  136.72956      0.01528  </code></pre>
</div>
</div>
<p><a href="http://parsnip.tidymodels.org"><code>parsnip</code></a> is package in <code>tidymodels</code> which is to provide a tidy, unified interface to models that can be used to try a range of models.</p>

<div class="no-row-height column-margin column-container"><div class="margin-aside">
<p>Note: The fit command does not follow the tidyverse principle the data comes first. Instead, the formula comes first. This is to relate to existing traditions of a much older established way of modeling in base R.</p>
</div></div></section>
<section id="what-does-the-output-say" class="level2 smaller" data-number="3.6">
<h2 class="smaller anchored" data-number="3.6" data-anchor-id="what-does-the-output-say"><span class="header-section-number">3.6</span> What does the output say?</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">linear_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">|&gt;</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(flipper_length_mm <span class="sc">~</span> body_mass_g, <span class="at">data =</span> penguins)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>parsnip model object


Call:
stats::lm(formula = flipper_length_mm ~ body_mass_g, data = data)

Coefficients:
(Intercept)  body_mass_g  
  136.72956      0.01528  </code></pre>
</div>
</div>
<p>. . .</p>
<p>average <code>flipper_length_mm</code> <span class="math inline">\(= 136.72956 + 0.01528\cdot\)</span> <code>body_mass_g</code></p>
<p>. . .</p>
<p><strong>Interpretation:</strong><br>
The penguins have a flipper length of 138 mm plus 0.01528 mm for each gram of body mass (that is 15.28 mm per kg). Penguins with zero mass have a flipper length of 138 mm. However, this is not in the range where the model was fitted.</p>
</section>
<section id="show-output-in-tidy-form" class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="show-output-in-tidy-form"><span class="header-section-number">3.7</span> Show output in <em>tidy</em> form</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">linear_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">|&gt;</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(flipper_length_mm <span class="sc">~</span> body_mass_g, <span class="at">data =</span> penguins) <span class="sc">|&gt;</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error statistic   p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept) 137.      2.00          68.5 5.71e-201
2 body_mass_g   0.0153  0.000467      32.7 4.37e-107</code></pre>
</div>
</div>
</section>
<section id="parameter-estimation" class="level2 smaller" data-background-color="aquamarine" data-number="3.8">
<h2 class="smaller anchored" data-background-color="aquamarine" data-number="3.8" data-anchor-id="parameter-estimation"><span class="header-section-number">3.8</span> Parameter estimation</h2>
<p>Notation from statistics: <span class="math inline">\(\beta\)</span>’s for the population parameters and <span class="math inline">\(\hat\beta\)</span>’s for the parameters estimated from the sample statistics.</p>
<p><span class="math display">\[\hat y = \beta_0 + \beta_1 x\]</span></p>
<p>The population parameters <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> we cannot have. (<span class="math inline">\(\hat y\)</span> stands for <em>predicted value of <span class="math inline">\(y\)</span></em>. )</p>
<p>. . .</p>
<p>Instead, we estimate <span class="math inline">\(\hat\beta_0\)</span> and <span class="math inline">\(\hat\beta_1\)</span> in the model fitting process.</p>
<p><span class="math display">\[\hat y = \hat\beta_0 + \hat\beta_1 x\]</span></p>
<div style="background-color:khaki;padding:10px;">
<p>A typical follow-up data analysis question is what the fitted values <span class="math inline">\(\hat\beta_0\)</span> and <span class="math inline">\(\hat\beta_1\)</span> tell us about the (unknown) population-wide values <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>?</p>
<p>This is the typical <span style="'color:blue"><strong>inferential question</strong></span>.</p>
</div>
</section>
<section id="parsnip-model-objects" class="level2 smaller" data-number="3.9">
<h2 class="smaller anchored" data-number="3.9" data-anchor-id="parsnip-model-objects"><span class="header-section-number">3.9</span> <code>parsnip</code> model objects</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>pengmod <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">|&gt;</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(flipper_length_mm <span class="sc">~</span> body_mass_g, <span class="at">data =</span> penguins)</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(pengmod) <span class="co"># attributes</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "_lm"       "model_fit"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">typeof</span>(pengmod)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "list"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(pengmod)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "lvl"          "ordered"      "spec"         "fit"          "preproc"     
[6] "elapsed"      "censor_probs"</code></pre>
</div>
</div>
<p>. . .</p>
<p>Most interesting for us for now: <code>$fit</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>pengmod<span class="sc">$</span>fit</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
stats::lm(formula = flipper_length_mm ~ body_mass_g, data = data)

Coefficients:
(Intercept)  body_mass_g  
  136.72956      0.01528  </code></pre>
</div>
</div>
<p>. . .</p>
<p>Notice: <code>parsnip model object</code> is now missing in the output.</p>
</section>
<section id="fit-is-the-object-created-by-lm-base-r" class="level2 smaller scrollable" data-number="3.10">
<h2 class="smaller scrollable anchored" data-number="3.10" data-anchor-id="fit-is-the-object-created-by-lm-base-r"><span class="header-section-number">3.10</span> <code>$fit</code> is the object created by <code>lm</code> (base R)</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(pengmod<span class="sc">$</span>fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "coefficients"  "residuals"     "effects"       "rank"         
 [5] "fitted.values" "assign"        "qr"            "df.residual"  
 [9] "na.action"     "xlevels"       "call"          "terms"        
[13] "model"        </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>pengmod<span class="sc">$</span>fit<span class="sc">$</span>call</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>stats::lm(formula = flipper_length_mm ~ body_mass_g, data = data)</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>pengmod<span class="sc">$</span>fit<span class="sc">$</span>coefficients</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept)  body_mass_g 
136.72955927   0.01527592 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>pengmod<span class="sc">$</span>fit<span class="sc">$</span>fitted.values</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2        3        5        6        7        8        9 
194.0142 194.7780 186.3763 189.4315 192.4867 192.1048 208.1445 189.8134 
      10       11       12       13       14       15       16       17 
201.6522 187.1401 193.2504 185.6125 194.7780 203.9436 193.2504 189.4315 
      18       19       20       21       22       23       24       25 
205.4712 187.5220 200.8884 188.6677 191.7229 194.7780 197.0694 194.7780 
      26       27       28       29       30       31       32       33 
194.7780 190.9591 185.6125 184.8487 197.0694 186.3763 196.3056 187.1401 
      34       35       36       37       38       39       40       41 
196.3056 187.5220 200.1246 197.0694 190.9591 187.1401 207.7626 184.8487 
      42       43       44       45       46       47       48       49 
196.3056 184.0849 203.9436 182.5573 206.9988 189.0496 182.1754 189.4315 
      50       51       52       53       54       55       56       57 
200.1246 190.1953 202.4160 189.4315 198.5970 181.0297 193.2504 190.9591 
      58       59       60       61       62       63       64       65 
194.7780 180.2659 194.0142 184.8487 203.9436 191.7229 198.5970 180.2659 
      66       67       68       69       70       71       72       73 
197.0694 187.9039 199.3608 183.3211 204.7074 191.7229 196.3056 190.9591 
      74       75       76       77       78       79       80       81 
200.1246 193.2504 201.6522 193.2504 196.3056 190.9591 197.8332 185.6125 
      82       83       84       85       86       87       88       89 
208.5264 194.7780 200.8884 187.9039 190.9591 194.7780 190.1953 197.0694 
      90       91       92       93       94       95       96       97 
191.7229 190.9591 202.4160 188.6677 204.7074 187.1401 202.4160 193.2504 
      98       99      100      101      102      103      104      105 
203.1798 181.0297 199.3608 193.6323 208.9083 183.7030 201.6522 181.4116 
     106      107      108      109      110      111      112      113 
190.9591 194.0142 196.3056 185.2306 209.6721 195.1599 206.9988 185.6125 
     114      115      116      117      118      119      120      121 
202.0341 196.3056 198.9789 181.0297 194.3961 187.9039 187.5220 184.8487 
     122      123      124      125      126      127      128      129 
190.1953 189.4315 195.9237 183.3211 197.8332 186.7582 202.4160 183.3211 
     130      131      132      133      134      135      136      137 
197.8332 187.5220 190.1953 190.1953 205.0893 189.0496 196.3056 185.2306 
     138      139      140      141      142      143      144      145 
197.4513 188.6677 201.6522 188.6677 189.8134 183.3211 193.6323 182.5573 
     146      147      148      149      150      151      152      153 
192.4867 201.6522 189.8134 189.4315 194.0142 193.2504 197.8332 205.4712 
     154      155      156      157      158      159      160      161 
223.8023 204.7074 223.8023 219.2195 206.2350 210.0540 216.1643 203.9436 
     162      163      164      165      166      167      168      169 
215.4005 207.7626 221.5109 207.7626 226.0937 200.8884 226.0937 200.1246 
     170      171      172      173      174      175      176      177 
232.9678 210.0540 218.4557 223.8023 213.1091 203.9436 213.8729 213.1091 
     178      179      180      181      182      183      184      185 
214.6367 199.3608 223.0385 206.9988 221.5109 216.9281 208.5264 213.8729 
     186      187      188      189      190      191      192      193 
229.1488 215.4005 219.2195 212.3453 216.9281 203.1798 218.4557 197.0694 
     194      195      196      197      198      199      200      201 
223.8023 202.4160 209.2902 221.5109 211.5815 200.8884 219.2195 214.6367 
     202      203      204      205      206      207      208      209 
217.6919 210.8177 217.6919 203.9436 213.1091 211.5815 213.8729 202.4160 
     210      211      212      213      214      215      216      217 
213.1091 204.7074 221.5109 200.8884 217.6919 203.9436 223.0385 208.5264 
     218      219      220      221      222      223      224      225 
223.8023 207.7626 225.3299 208.5264 221.5109 209.2902 213.1091 214.6367 
     226      227      228      229      230      231      232      233 
216.1643 208.5264 225.3299 206.9988 228.3851 209.2902 227.6213 207.3807 
     234      235      236      237      238      239      240      241 
219.9833 208.9083 218.4557 209.2902 222.2747 206.9988 217.6919 211.1996 
     242      243      244      245      246      247      248      249 
221.5109 212.3453 219.2195 209.2902 223.0385 210.8177 216.1643 211.9634 
     250      251      252      253      254      255      256      257 
211.1996 207.3807 216.9281 210.8177 222.2747 212.7272 220.7471 208.9083 
     258      259      260      261      262      263      264      265 
220.7471 208.5264 220.7471 206.6169 220.7471 213.1091 227.6213 207.7626 
     266      267      268      269      270      271      273      274 
220.7471 203.5617 226.0937 211.1996 228.3851 211.9634 210.8177 224.5661 
     275      276      277      278      279      280      281      282 
216.1643 219.2195 190.1953 196.3056 192.4867 190.5772 193.6323 197.0694 
     283      284      285      286      287      288      289      290 
186.3763 194.0142 200.1246 193.2504 194.7780 194.3961 193.2504 198.5970 
     291      292      293      294      295      296      297      298 
191.3410 198.5970 187.1401 193.2504 189.4315 203.9436 191.7229 188.6677 
     299      300      301      302      303      304      305      306 
181.0297 194.7780 187.1401 200.1246 188.6677 194.7780 193.2504 206.2350 
     307      308      309      310      311      312      313      314 
185.6125 202.4160 187.9039 199.3608 191.7229 196.3056 195.5418 210.0540 
     315      316      317      318      319      320      321      322 
177.9745 205.4712 197.0694 192.4867 190.9591 190.1953 192.8685 204.7074 
     323      324      325      326      327      328      329      330 
188.6677 202.4160 186.3763 192.8685 187.5220 197.0694 191.7229 198.5970 
     331      332      333      334      335      336      337      338 
187.9039 189.4315 186.3763 198.5970 194.7780 190.5772 197.0694 192.4867 
     339      340      341      342      343      344 
192.4867 197.8332 188.6677 194.3961 199.3608 194.3961 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>pengmod<span class="sc">$</span>fit<span class="sc">$</span>residuals</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           1            2            3            5            6            7 
-13.01424280  -8.77803858   8.62371500   3.56853188  -2.48665124 -11.10475335 
           8            9           10           11           12           13 
-13.14446474   3.18663399 -11.65220061  -1.14008078 -13.25044702  -3.61248922 
          14           15           16           17           18           19 
 -3.77803858  -5.94358795  -8.25044702   5.56853188  -8.47117951  -3.52197867 
          20           21           22           23           24           25 
 -6.88840483 -14.66767234 -11.72285546  -5.77803858 -12.06942592 -14.77803858 
          26           27           28           29           30           31 
 -7.77803858  -7.95905968   1.38751078 -12.84869344 -17.06942592  -8.37628500 
          32           33           34           35           36           37 
-18.30563014   0.85991922 -12.30563014   7.47802133  -4.12460905  -7.06942592 
          38           39           40           41           42           43 
-10.95905968  -6.14008078 -23.76256685  -2.84869344  -1.30563014   1.91510234 
          44           45           46           47           48           49 
 -7.94358795   2.44269390 -16.99877107  -7.04957023  -3.17540821   0.56853188 
          50           51           52           53           54           55 
 -9.12460905  -4.19526390 -14.41599639   0.56853188   1.40298251   5.97028546 
          56           57           58           59           60           61 
 -2.25044702  -4.95905968  -1.77803858   0.73408124  -0.01424280   0.15130656 
          62           63           64           65           66           67 
 -8.94358795  -6.72285546  -6.59701749   3.73408124  -5.06942592   7.09612344 
          68           69           70           71           72           73 
-11.36081327   6.67889812  -6.70738373  -1.72285546  -6.30563014   5.04094032 
          74           75           76           77           78           79 
 -3.12460905  -3.25044702  -6.65220061  -2.25044702 -12.30563014  -3.95905968 
          80           81           82           83           84           85 
 -2.83322170   3.38751078 -12.52636263  -7.77803858  -7.88840483   3.09612344 
          86           87           88           89           90           91 
  3.04094032  -4.77803858  -1.19526390  -8.06942592  -1.72285546  11.04094032 
          92           93           94           95           96           97 
  2.58400361  -3.66767234 -18.70738373  -0.14008078   5.58400361  -3.25044702 
          98           99          100          101          102          103 
 -7.17979217  -3.02971454  -7.36081327  -1.63234491  -5.90826052  -0.70299977 
         104          105          106          107          108          109 
-11.65220061  11.58838757  -6.95905968   4.98575720  -6.30563014  -4.23059133 
         110          111          112          113          114          115 
-12.67205630   2.84006353 -15.99877107   7.38751078  -5.03409850  -5.30563014 
         116          117          118          119          120          121 
 -2.97891538   6.97028546   4.60385931   1.09612344   1.47802133   2.15130656 
         122          123          124          125          126          127 
  7.80473610 -13.43146812   6.07626775   2.67889812   1.16677830   4.24181711 
         128          129          130          131          132          133 
 -7.41599639   7.67889812  12.16677830   2.47802133   6.80473610   2.80473610 
         134          135          136          137          138          139 
 -6.08928162  -2.04957023  -6.30563014   5.76940867   2.54867619  -3.66767234 
         140          141          142          143          144          145 
 -8.65220061   4.33232766  -2.81336601   4.67889812  -3.63234491   9.44269390 
         146          147          148          149          150          151 
 -7.48665124 -11.65220061  -5.81336601   5.56853188  -1.01424280  -6.25044702 
         152          153          154          155          156          157 
  3.16677830   5.52882049   6.19772176   5.29261627  -5.80227824  -4.21950356 
         158          159          160          161          162          163 
  3.76502471   0.94604581   2.83567957   5.05641205  -0.40052465   6.23743315 
         164          165          166          167          168          169 
 -5.51089090   6.23743315 -13.09366558   9.11159517  -9.09366558   9.87539095 
         170          171          172          173          174          175 
-11.96782760  -1.05395419   3.54429222  -5.80227824   1.89086269   9.05641205 
         176          177          178          179          180          181 
  1.12706691   1.89086269   0.36327113  16.63918673  -8.03848246   3.00122893 
         182          183          184          185          186          187 
 -1.51089090   5.07188379   0.47363737  -6.87293309   0.85115130   4.59947535 
         188          189          190          191          192          193 
  0.78049644   0.65465847   2.07188379   4.82020783 -10.45570778  10.93057408 
         194          195          196          197          198          199 
  1.19772176   7.58400361   6.70984159   0.48910910   5.41845425   9.11159517 
         200          201          202          203          204          205 
  5.78049644  -1.63672887  -2.69191200  -0.81774997   2.30808800   6.05641205 
         206          207          208          209          210          211 
 11.89086269   5.41845425   6.12706691   5.58400361   6.89086269   3.29261627 
         212          213          214          215          216          217 
  2.48910910   7.11159517   3.30808800  10.05641205   7.96151754  10.47363737 
         218          219          220          221          222          223 
  6.19772176   6.23743315   3.67013020  11.47363737   1.48910910   6.70984159 
         224          225          226          227          228          229 
  7.89086269   6.36327113   0.83567957   7.47363737   4.67013020   2.00122893 
         230          231          232          233          234          235 
 -8.38505292   5.70984159  -4.62125714   4.61933104   1.01670066   3.09173948 
         236          237          238          239          240          241 
  5.54429222   2.70984159   5.72531332  11.00122893   0.30808800   0.80035214 
         242          243          244          245          246          247 
  8.48910910   5.65465847   8.78049644   2.70984159   0.96151754   3.18225003 
         248          249          250          251          252          253 
  9.83567957   4.03655636  10.80035214  -4.38066896   8.07188379   8.18225003 
         254          255          256          257          258          259 
  5.72531332   2.27276058   7.25290488   7.09173948  -5.74709512   1.47363737 
         260          261          262          263          264          265 
 -1.74709512   1.38312682 -11.74709512   2.89086269   1.37874286   5.23743315 
         266          267          268          269          270          271 
  9.25290488  13.43830994   3.90633442   5.80035214  -6.38505292   2.03655636 
         273          274          275          276          277          278 
  4.18225003  -2.56607402  -4.16432043  -6.21950356   1.80473610  -0.30563014 
         279          280          281          282          283          284 
  0.51334876  -2.57716179   3.36765509   0.93057408  -8.37628500   2.98575720 
         285          286          287          288          289          290 
 -5.12460905   4.74955298  -1.77803858  -0.39614069  -8.25044702   2.40298251 
         291          292          293          294          295          296 
 -1.34095757   2.40298251   9.85991922 -12.25044702   0.56853188  -8.94358795 
         297          298          299          300          301          302 
-10.72285546   2.33232766   5.97028546  -1.77803858   7.85991922  -3.12460905 
         303          304          305          306          307          308 
 11.33232766   5.22196142  -2.25044702  -1.23497529   1.38751078  -1.41599639 
         309          310          311          312          313          314 
 -0.90387656   3.63918673   3.27714454   2.69436986  -0.54183436  -0.05395419 
         315          316          317          318          319          320 
 14.02546859  -0.47117951  12.93057408  -5.48665124   5.04094032   5.80473610 
         321          322          323          324          325          326 
  3.13145087  -3.70738373   1.33232766   9.58400361   0.62371500   5.13145087 
         327          328          329          330          331          332 
 11.47802133   3.93057408   1.27714454   4.40298251  -0.90387656   7.56853188 
         333          334          335          336          337          338 
  4.62371500   4.40298251   7.22196142   3.42283821   8.93057408  -3.48665124 
         339          340          341          342          343          344 
  2.51334876   9.16677830  13.33232766  -1.39614069  10.63918673   3.60385931 </code></pre>
</div>
</div>
</section>
<section id="fitting-method-least-squares-regression" class="level2 smaller" data-background-color="aquamarine" data-number="3.11">
<h2 class="smaller anchored" data-background-color="aquamarine" data-number="3.11" data-anchor-id="fitting-method-least-squares-regression"><span class="header-section-number">3.11</span> Fitting method: Least squares regression</h2>
<ul>
<li>The regression line shall minimize the sum of the squared residuals<br>
(or, identically, their mean).</li>
<li>Mathematically: The residual for case <span class="math inline">\(i\)</span> is <span class="math inline">\(e_i = \hat y_i - y_i\)</span>.</li>
<li>Now we want to minimize <span class="math inline">\(\sum_{i=1}^n e_i^2\)</span><br>
(or equivalently <span class="math inline">\(\frac{1}{n}\sum_{i=1}^n e_i^2\)</span> the <em>mean of squared errors</em>, which we will look at later).</li>
</ul>
</section>
<section id="visualization-of-residuals" class="level2 smaller scrollable" data-background-color="aquamarine" data-number="3.12">
<h2 class="smaller scrollable anchored" data-background-color="aquamarine" data-number="3.12" data-anchor-id="visualization-of-residuals"><span class="header-section-number">3.12</span> Visualization of residuals</h2>
<p>The residuals are the gray lines between predicted values on the regression line and the actual values.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>pengmod <span class="ot">&lt;-</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">linear_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">|&gt;</span></span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(flipper_length_mm <span class="sc">~</span> body_mass_g, <span class="at">data =</span> penguins)</span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>penguins <span class="sc">|&gt;</span></span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(<span class="fu">predict</span>(pengmod, penguins)) <span class="sc">|&gt;</span></span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(body_mass_g, flipper_length_mm)) <span class="sc">+</span></span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(</span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(</span>
<span id="cb72-10"><a href="#cb72-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">x =</span> body_mass_g,</span>
<span id="cb72-11"><a href="#cb72-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">y =</span> flipper_length_mm,</span>
<span id="cb72-12"><a href="#cb72-12" aria-hidden="true" tabindex="-1"></a>      <span class="at">xend =</span> body_mass_g,</span>
<span id="cb72-13"><a href="#cb72-13" aria-hidden="true" tabindex="-1"></a>      <span class="at">yend =</span> .pred</span>
<span id="cb72-14"><a href="#cb72-14" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb72-15"><a href="#cb72-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"gray"</span></span>
<span id="cb72-16"><a href="#cb72-16" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb72-17"><a href="#cb72-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb72-18"><a href="#cb72-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb72-19"><a href="#cb72-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> .pred), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values or values outside the scale range
(`geom_segment()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values or values outside the scale range
(`geom_point()`).
Removed 2 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W07_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="check-fitted-values-and-residuals" class="level2 smaller scrollable" data-background-color="aquamarine" data-number="3.13">
<h2 class="smaller scrollable anchored" data-background-color="aquamarine" data-number="3.13" data-anchor-id="check-fitted-values-and-residuals"><span class="header-section-number">3.13</span> Check: Fitted values and Residuals</h2>
<p>Recall: <strong>Residual = Observed value - Predicted value</strong></p>
<p>The <em>Predicted values</em> are also called <em>Fitted values</em>. Hence:</p>
<p>Residuals + Fitted values = Observed values</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>pengmod<span class="sc">$</span>fit<span class="sc">$</span>residuals <span class="sc">+</span> pengmod<span class="sc">$</span>fit<span class="sc">$</span>fitted.values</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  1   2   3   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21 
181 186 195 193 190 181 195 193 190 186 180 182 191 198 185 195 197 184 194 174 
 22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41 
180 189 185 180 187 183 187 172 180 178 178 188 184 195 196 190 180 181 184 182 
 42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61 
195 186 196 185 190 182 179 190 191 186 188 190 200 187 191 186 193 181 194 185 
 62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81 
195 185 192 184 192 195 188 190 198 190 190 196 197 190 195 191 184 187 195 189 
 82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101 
196 187 193 191 194 190 189 189 190 202 205 185 186 187 208 190 196 178 192 192 
102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 
203 183 190 193 184 199 190 181 197 198 191 193 197 191 196 188 199 189 189 187 
122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 
198 176 202 186 199 191 195 191 210 190 197 193 199 187 190 191 200 185 193 193 
142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 
187 188 190 192 185 190 184 195 193 187 201 211 230 210 218 215 210 211 219 209 
162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 
215 214 216 214 213 210 217 210 221 209 222 218 215 213 215 215 215 216 215 210 
182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 
220 222 209 207 230 220 220 213 219 208 208 208 225 210 216 222 217 210 225 213 
202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 
215 210 220 210 225 217 220 208 220 208 224 208 221 214 231 219 230 214 229 220 
222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 
223 216 221 221 217 216 230 209 220 215 223 212 221 212 224 212 228 218 218 212 
242 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261 
230 218 228 212 224 214 226 216 222 203 225 219 228 215 228 216 215 210 219 208 
262 263 264 265 266 267 268 269 270 271 273 274 275 276 277 278 279 280 281 282 
209 216 229 213 230 217 230 217 222 214 215 222 212 213 192 196 193 188 197 198 
283 284 285 286 287 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 
178 197 195 198 193 194 185 201 190 201 197 181 190 195 181 191 187 193 195 197 
303 304 305 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 
200 200 191 205 187 201 187 203 195 199 195 210 192 205 210 187 196 196 196 201 
323 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342 
190 212 187 198 199 201 193 203 187 197 191 203 202 194 206 189 195 207 202 193 
343 344 
210 198 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>penguins<span class="sc">$</span>flipper_length_mm</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] 181 186 195  NA 193 190 181 195 193 190 186 180 182 191 198 185 195 197
 [19] 184 194 174 180 189 185 180 187 183 187 172 180 178 178 188 184 195 196
 [37] 190 180 181 184 182 195 186 196 185 190 182 179 190 191 186 188 190 200
 [55] 187 191 186 193 181 194 185 195 185 192 184 192 195 188 190 198 190 190
 [73] 196 197 190 195 191 184 187 195 189 196 187 193 191 194 190 189 189 190
 [91] 202 205 185 186 187 208 190 196 178 192 192 203 183 190 193 184 199 190
[109] 181 197 198 191 193 197 191 196 188 199 189 189 187 198 176 202 186 199
[127] 191 195 191 210 190 197 193 199 187 190 191 200 185 193 193 187 188 190
[145] 192 185 190 184 195 193 187 201 211 230 210 218 215 210 211 219 209 215
[163] 214 216 214 213 210 217 210 221 209 222 218 215 213 215 215 215 216 215
[181] 210 220 222 209 207 230 220 220 213 219 208 208 208 225 210 216 222 217
[199] 210 225 213 215 210 220 210 225 217 220 208 220 208 224 208 221 214 231
[217] 219 230 214 229 220 223 216 221 221 217 216 230 209 220 215 223 212 221
[235] 212 224 212 228 218 218 212 230 218 228 212 224 214 226 216 222 203 225
[253] 219 228 215 228 216 215 210 219 208 209 216 229 213 230 217 230 217 222
[271] 214  NA 215 222 212 213 192 196 193 188 197 198 178 197 195 198 193 194
[289] 185 201 190 201 197 181 190 195 181 191 187 193 195 197 200 200 191 205
[307] 187 201 187 203 195 199 195 210 192 205 210 187 196 196 196 201 190 212
[325] 187 198 199 201 193 203 187 197 191 203 202 194 206 189 195 207 202 193
[343] 210 198</code></pre>
</div>
</div>
</section>
</section>
<section id="nonlinear-models" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Nonlinear Models</h1>
<section id="when-a-linear-model-is-bad" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="when-a-linear-model-is-bad"><span class="header-section-number">4.1</span> When a linear model is bad</h2>
<p>Example: Total corona cases in Germany in the first wave 2020.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>whofull <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"WHO-COVID-19-global-data.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Country <span class="sc">==</span> <span class="st">"Germany"</span>)</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>who <span class="ot">&lt;-</span> whofull <span class="sc">|&gt;</span></span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Date_reported <span class="sc">&lt;</span> <span class="st">"2020-03-20"</span>, Date_reported <span class="sc">&gt;</span> <span class="st">"2020-02-25"</span>)</span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>who <span class="sc">|&gt;</span></span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Date_reported, Cumulative_cases)) <span class="sc">+</span></span>
<span id="cb81-7"><a href="#cb81-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb81-8"><a href="#cb81-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb81-9"><a href="#cb81-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W07_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="log-transformation" class="level2 smaller" data-number="4.2">
<h2 class="smaller anchored" data-number="4.2" data-anchor-id="log-transformation"><span class="header-section-number">4.2</span> <span class="math inline">\(\log\)</span> transformation</h2>
<p>Instead of <code>Cumulative_cases</code> we look at <span class="math inline">\(\log(\)</span><code>Cumulative_cases</code><span class="math inline">\()\)</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>who <span class="sc">|&gt;</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Date_reported, <span class="fu">log</span>(Cumulative_cases))) <span class="sc">+</span></span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb83-6"><a href="#cb83-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">20</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W07_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Almost perfect fit of the linear model: <span class="math inline">\(\log(y)=\log(\beta_0) + \beta_1\cdot x\)</span><br>
(<span class="math inline">\(y=\)</span> <code>Cumulative cases</code>, <span class="math inline">\(x=\)</span> Days)</p>
<p>. . .</p>
<p>Exponentiation gives the model: <span class="math inline">\(y=\beta_0 e^{\beta_1\cdot x}\)</span><br>
(Check <span class="math inline">\(e^{\log(\beta_0) + \beta_1\cdot x} = e^{\log(\beta_0)} e^{\beta_1\cdot x} = \beta_0 e^{\beta_1\cdot x}\)</span>)</p>
</section>
<section id="exponential-growth" class="level2 smaller" data-number="4.3">
<h2 class="smaller anchored" data-number="4.3" data-anchor-id="exponential-growth"><span class="header-section-number">4.3</span> Exponential growth!</h2>
<p><span style="color:red;"><span class="math inline">\(y=\beta_0 e^{\beta_1\cdot x}\)</span></span><br>
For comparison: Logistic function <span style="color:blue;"><span class="math inline">\(y = \frac{N \beta_0 e^{\beta_1\cdot x}}{N + \beta_0 e^{\beta_1\cdot x}}\)</span></span> for <span class="math inline">\(N=200000\)</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>wholm <span class="ot">&lt;-</span> who <span class="sc">|&gt;</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(<span class="fu">log</span>(Cumulative_cases) <span class="sc">~</span> Date_reported, <span class="at">data =</span> _)</span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>who <span class="sc">|&gt;</span></span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Date_reported, Cumulative_cases)) <span class="sc">+</span></span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb85-6"><a href="#cb85-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb85-7"><a href="#cb85-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_function</span>(</span>
<span id="cb85-8"><a href="#cb85-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">fun =</span> <span class="cf">function</span>(x) <span class="fu">exp</span>(<span class="fu">coef</span>(wholm)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(wholm)[<span class="dv">2</span>] <span class="sc">*</span> <span class="fu">as.numeric</span>(x)),</span>
<span id="cb85-9"><a href="#cb85-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"red"</span></span>
<span id="cb85-10"><a href="#cb85-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb85-11"><a href="#cb85-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_function</span>(</span>
<span id="cb85-12"><a href="#cb85-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">fun =</span> <span class="cf">function</span>(x) {</span>
<span id="cb85-13"><a href="#cb85-13" aria-hidden="true" tabindex="-1"></a>      <span class="dv">200000</span> <span class="sc">*</span></span>
<span id="cb85-14"><a href="#cb85-14" aria-hidden="true" tabindex="-1"></a>        <span class="fu">exp</span>(<span class="fu">coef</span>(wholm)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(wholm)[<span class="dv">2</span>] <span class="sc">*</span> <span class="fu">as.numeric</span>(x)) <span class="sc">/</span></span>
<span id="cb85-15"><a href="#cb85-15" aria-hidden="true" tabindex="-1"></a>        (<span class="dv">200000</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="fu">coef</span>(wholm)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(wholm)[<span class="dv">2</span>] <span class="sc">*</span> <span class="fu">as.numeric</span>(x)))</span>
<span id="cb85-16"><a href="#cb85-16" aria-hidden="true" tabindex="-1"></a>    },</span>
<span id="cb85-17"><a href="#cb85-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"blue"</span></span>
<span id="cb85-18"><a href="#cb85-18" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb85-19"><a href="#cb85-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">20</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W07_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Logistic growth (as in the SI model) mimicks exponential growth initially.</p>
</section>
<section id="log-transformation-1" class="level2 smaller" data-number="4.4">
<h2 class="smaller anchored" data-number="4.4" data-anchor-id="log-transformation-1"><span class="header-section-number">4.4</span> <span class="math inline">\(\log\)</span> transformation</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>who <span class="sc">|&gt;</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Date_reported, <span class="fu">log10</span>(Cumulative_cases))) <span class="sc">+</span></span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W07_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>An important difference of <code>log10(Cumulative_cases) ~ Date_Reported</code> to the penguin model <code>flipper_length_mm ~ body_mass_g</code>? ?</p>
<p>. . .</p>
<ul>
<li><span class="math inline">\(x\)</span> has an ordered structure and no duplicates</li>
</ul>
<p>The fit looks so good. Why?</p>
<p>. . .</p>
<p>Because there is a <em>mechanistic explanation</em> behind: The SI model.</p>
</section>
<section id="however-it-works-only-in-a-certain-range" class="level2 smaller" data-number="4.5">
<h2 class="smaller anchored" data-number="4.5" data-anchor-id="however-it-works-only-in-a-certain-range"><span class="header-section-number">4.5</span> However, it works only in a certain range</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>who <span class="sc">|&gt;</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Date_reported, Cumulative_cases)) <span class="sc">+</span></span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_function</span>(</span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">fun =</span> <span class="cf">function</span>(x) <span class="fu">exp</span>(<span class="fu">coef</span>(wholm)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(wholm)[<span class="dv">2</span>] <span class="sc">*</span> <span class="fu">as.numeric</span>(x)),</span>
<span id="cb88-6"><a href="#cb88-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"red"</span></span>
<span id="cb88-7"><a href="#cb88-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb88-8"><a href="#cb88-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_function</span>(</span>
<span id="cb88-9"><a href="#cb88-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">fun =</span> <span class="cf">function</span>(x) {</span>
<span id="cb88-10"><a href="#cb88-10" aria-hidden="true" tabindex="-1"></a>      <span class="dv">200000</span> <span class="sc">*</span></span>
<span id="cb88-11"><a href="#cb88-11" aria-hidden="true" tabindex="-1"></a>        <span class="fu">exp</span>(<span class="fu">coef</span>(wholm)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(wholm)[<span class="dv">2</span>] <span class="sc">*</span> <span class="fu">as.numeric</span>(x)) <span class="sc">/</span></span>
<span id="cb88-12"><a href="#cb88-12" aria-hidden="true" tabindex="-1"></a>        (<span class="dv">200000</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="fu">coef</span>(wholm)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(wholm)[<span class="dv">2</span>] <span class="sc">*</span> <span class="fu">as.numeric</span>(x)))</span>
<span id="cb88-13"><a href="#cb88-13" aria-hidden="true" tabindex="-1"></a>    },</span>
<span id="cb88-14"><a href="#cb88-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"blue"</span></span>
<span id="cb88-15"><a href="#cb88-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb88-16"><a href="#cb88-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">20</span>) <span class="sc">+</span></span>
<span id="cb88-17"><a href="#cb88-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> whofull <span class="sc">|&gt;</span> <span class="fu">filter</span>(Date_reported <span class="sc">&lt;</span> <span class="st">"2020-06-30"</span>)) <span class="sc">+</span></span>
<span id="cb88-18"><a href="#cb88-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">300000</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 52 rows containing missing values or values outside the scale range
(`geom_function()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W07_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="however-it-works-only-in-a-certain-range-log-scale-on-y" class="level2 smaller" data-number="4.6">
<h2 class="smaller anchored" data-number="4.6" data-anchor-id="however-it-works-only-in-a-certain-range-log-scale-on-y"><span class="header-section-number">4.6</span> However, it works only in a certain range (log scale on y)</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>who <span class="sc">|&gt;</span></span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Date_reported, Cumulative_cases)) <span class="sc">+</span></span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_function</span>(</span>
<span id="cb90-5"><a href="#cb90-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">fun =</span> <span class="cf">function</span>(x) <span class="fu">exp</span>(<span class="fu">coef</span>(wholm)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(wholm)[<span class="dv">2</span>] <span class="sc">*</span> <span class="fu">as.numeric</span>(x)),</span>
<span id="cb90-6"><a href="#cb90-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"red"</span></span>
<span id="cb90-7"><a href="#cb90-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb90-8"><a href="#cb90-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_function</span>(</span>
<span id="cb90-9"><a href="#cb90-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">fun =</span> <span class="cf">function</span>(x) {</span>
<span id="cb90-10"><a href="#cb90-10" aria-hidden="true" tabindex="-1"></a>      <span class="dv">200000</span> <span class="sc">*</span></span>
<span id="cb90-11"><a href="#cb90-11" aria-hidden="true" tabindex="-1"></a>        <span class="fu">exp</span>(<span class="fu">coef</span>(wholm)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(wholm)[<span class="dv">2</span>] <span class="sc">*</span> <span class="fu">as.numeric</span>(x)) <span class="sc">/</span></span>
<span id="cb90-12"><a href="#cb90-12" aria-hidden="true" tabindex="-1"></a>        (<span class="dv">200000</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="fu">coef</span>(wholm)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(wholm)[<span class="dv">2</span>] <span class="sc">*</span> <span class="fu">as.numeric</span>(x)))</span>
<span id="cb90-13"><a href="#cb90-13" aria-hidden="true" tabindex="-1"></a>    },</span>
<span id="cb90-14"><a href="#cb90-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"blue"</span></span>
<span id="cb90-15"><a href="#cb90-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb90-16"><a href="#cb90-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">20</span>) <span class="sc">+</span></span>
<span id="cb90-17"><a href="#cb90-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> whofull <span class="sc">|&gt;</span> <span class="fu">filter</span>(Date_reported <span class="sc">&lt;</span> <span class="st">"2020-06-30"</span>)) <span class="sc">+</span></span>
<span id="cb90-18"><a href="#cb90-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">300000</span>)) <span class="sc">+</span></span>
<span id="cb90-19"><a href="#cb90-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_log10</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Scale for y is already present.
Adding another scale for y, which will replace the existing scale.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in scale_y_log10(): log-10 transformation introduced infinite values.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W07_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>


</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>This a scale and a shift in the <span class="math inline">\(y\)</span> direction. Note: For lines there is always an analog transformations on the <span class="math inline">\(x\)</span> direction.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>loess = locally estimated scatterplot smoothing<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Also <strong>dependent variable</strong> in statistics or empirical social sciences.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Also <strong>independent variable(s)</strong> in statistics or empirical social sciences.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>