<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jan Lorenz">

<title>W#11: Collaborative Git, More Prediction Modeling, Quantifying Uncertainty, Crowd Wisdom – Data Science Concepts / Data Science Tools</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-16b4b51782fe9067b751a2cdf7d3de3a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed slimcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Data Science Concepts / Data Science Tools</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../index.html" aria-current="page"> 
<span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../schedule.html"> 
<span class="menu-text">Schedule</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/CU-F25-MDSSB-01-Concepts-Tools"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text">CU-F25-MDSSB-01-Concepts-Tools</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">W#11: Collaborative Git, More Prediction Modeling, Quantifying Uncertainty, Crowd Wisdom</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
  <div id="quarto-announcement" data-announcement-id="0f8f92da8bb6fd80db00a7a45d195a06" class="alert alert-warning hidden"><i class="bi bi-info-circle quarto-announcement-icon"></i><div class="quarto-announcement-content">
<p><a href="https://forms.office.com/e/75qEdyZbim"><strong>Data Science Tools Final Project Check-In</strong></a> open! Deadline Sat, Nov 8.</p>
</div><i class="bi bi-x-lg quarto-announcement-action"></i></div>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Syllabus</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../schedule.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Schedule</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../material/M01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">W#01</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../material/M02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">W#02</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../material/M03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">W#03</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../material/M04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">W#04</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../material/M05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">W#05</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../material/M06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">W#06</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../material/M07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">W#07</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../material/M08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">W#08</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../material/M09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">W#09</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../material/M10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">W#10</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../material/M11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">W#11</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../material/M12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">W#12</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Checklist Technical Setup</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../literature.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Learning Resources</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../homework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Homework Projects</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../final.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Final Project</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../help.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Need help for Homework?</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#preliminary" id="toc-preliminary" class="nav-link active" data-scroll-target="#preliminary"><span class="header-section-number">0.1</span> Preliminary</a></li>
  <li><a href="#final-project" id="toc-final-project" class="nav-link" data-scroll-target="#final-project"><span class="header-section-number">1</span> Final Project</a>
  <ul class="collapse">
  <li><a href="#a-project-report-in-a-nutshell" id="toc-a-project-report-in-a-nutshell" class="nav-link" data-scroll-target="#a-project-report-in-a-nutshell"><span class="header-section-number">1.1</span> A project report in a nutshell</a></li>
  <li><a href="#six-types-of-questions" id="toc-six-types-of-questions" class="nav-link" data-scroll-target="#six-types-of-questions"><span class="header-section-number">1.2</span> Six types of questions</a></li>
  <li><a href="#what-are-good-questions" id="toc-what-are-good-questions" class="nav-link" data-scroll-target="#what-are-good-questions"><span class="header-section-number">1.3</span> What are good questions?</a></li>
  <li><a href="#tools-and-advice-for-questions" id="toc-tools-and-advice-for-questions" class="nav-link" data-scroll-target="#tools-and-advice-for-questions"><span class="header-section-number">1.4</span> Tools and advice for questions</a></li>
  <li><a href="#tools-and-advice-for-questions-1" id="toc-tools-and-advice-for-questions-1" class="nav-link" data-scroll-target="#tools-and-advice-for-questions-1"><span class="header-section-number">1.5</span> Tools and advice for questions</a></li>
  <li><a href="#modeling-mindsets" id="toc-modeling-mindsets" class="nav-link" data-scroll-target="#modeling-mindsets"><span class="header-section-number">1.6</span> Modeling Mindsets</a></li>
  </ul></li>
  <li><a href="#collaborative-work-git" id="toc-collaborative-work-git" class="nav-link" data-scroll-target="#collaborative-work-git"><span class="header-section-number">2</span> Collaborative Work: Git</a>
  <ul class="collapse">
  <li><a href="#step-1-git-clone-finalproject_" id="toc-step-1-git-clone-finalproject_" class="nav-link" data-scroll-target="#step-1-git-clone-finalproject_"><span class="header-section-number">2.1</span> Step 1: git clone <code>FinalProject_*</code></a></li>
  <li><a href="#step-2-first-team-member-commits-and-pushes" id="toc-step-2-first-team-member-commits-and-pushes" class="nav-link" data-scroll-target="#step-2-first-team-member-commits-and-pushes"><span class="header-section-number">2.2</span> Step 2: First Team member commits and pushes</a></li>
  <li><a href="#step-3-other-team-members-pull" id="toc-step-3-other-team-members-pull" class="nav-link" data-scroll-target="#step-3-other-team-members-pull"><span class="header-section-number">2.3</span> Step 3: Other team members pull</a></li>
  <li><a href="#step-4-merge-independent-changes" id="toc-step-4-merge-independent-changes" class="nav-link" data-scroll-target="#step-4-merge-independent-changes"><span class="header-section-number">2.4</span> Step 4: Merge independent changes</a></li>
  <li><a href="#git-configuration-for-divergent-branches" id="toc-git-configuration-for-divergent-branches" class="nav-link" data-scroll-target="#git-configuration-for-divergent-branches"><span class="header-section-number">2.5</span> ??? <code>git</code> configuration for divergent branches</a></li>
  <li><a href="#step-5-push-and-pull-the-other-way-round" id="toc-step-5-push-and-pull-the-other-way-round" class="nav-link" data-scroll-target="#step-5-push-and-pull-the-other-way-round"><span class="header-section-number">2.6</span> Step 5: Push and pull the other way round</a></li>
  <li><a href="#step-6-create-a-merge-conflict" id="toc-step-6-create-a-merge-conflict" class="nav-link" data-scroll-target="#step-6-create-a-merge-conflict"><span class="header-section-number">2.7</span> Step 6: Create a merge conflict</a></li>
  <li><a href="#step-7-solve-the-conflict" id="toc-step-7-solve-the-conflict" class="nav-link" data-scroll-target="#step-7-solve-the-conflict"><span class="header-section-number">2.8</span> Step 7: Solve the conflict</a></li>
  <li><a href="#advice-collaborative-work-with-git" id="toc-advice-collaborative-work-with-git" class="nav-link" data-scroll-target="#advice-collaborative-work-with-git"><span class="header-section-number">2.9</span> Advice: Collaborative work with git</a></li>
  </ul></li>
  <li><a href="#more-prediction-modeling-cross-validation-tuning-random-forests" id="toc-more-prediction-modeling-cross-validation-tuning-random-forests" class="nav-link" data-scroll-target="#more-prediction-modeling-cross-validation-tuning-random-forests"><span class="header-section-number">3</span> More Prediction Modeling: Cross-Validation, Tuning, Random Forests</a>
  <ul class="collapse">
  <li><a href="#workflow-prediction-model" id="toc-workflow-prediction-model" class="nav-link" data-scroll-target="#workflow-prediction-model"><span class="header-section-number">3.1</span> Workflow prediction model</a></li>
  <li><a href="#decision-tree" id="toc-decision-tree" class="nav-link" data-scroll-target="#decision-tree"><span class="header-section-number">3.2</span> Decision Tree</a></li>
  <li><a href="#decision-tree-hyper-parameters" id="toc-decision-tree-hyper-parameters" class="nav-link" data-scroll-target="#decision-tree-hyper-parameters"><span class="header-section-number">3.3</span> Decision Tree: Hyper-Parameters</a></li>
  <li><a href="#how-reliable-are-performance-metrics" id="toc-how-reliable-are-performance-metrics" class="nav-link" data-scroll-target="#how-reliable-are-performance-metrics"><span class="header-section-number">3.4</span> How reliable are performance metrics?</a></li>
  <li><a href="#cross-validation" id="toc-cross-validation" class="nav-link" data-scroll-target="#cross-validation"><span class="header-section-number">3.5</span> Cross-validation</a></li>
  <li><a href="#cross-validation-1" id="toc-cross-validation-1" class="nav-link" data-scroll-target="#cross-validation-1"><span class="header-section-number">3.6</span> Cross-validation</a></li>
  <li><a href="#tuning" id="toc-tuning" class="nav-link" data-scroll-target="#tuning"><span class="header-section-number">3.7</span> Tuning</a></li>
  <li><a href="#tuning-continued" id="toc-tuning-continued" class="nav-link" data-scroll-target="#tuning-continued"><span class="header-section-number">3.8</span> Tuning continued</a></li>
  <li><a href="#tuning-continued-1" id="toc-tuning-continued-1" class="nav-link" data-scroll-target="#tuning-continued-1"><span class="header-section-number">3.9</span> Tuning continued</a></li>
  <li><a href="#fit-with-tune-parameters" id="toc-fit-with-tune-parameters" class="nav-link" data-scroll-target="#fit-with-tune-parameters"><span class="header-section-number">3.10</span> Fit with tune parameters</a></li>
  <li><a href="#random-forests" id="toc-random-forests" class="nav-link" data-scroll-target="#random-forests"><span class="header-section-number">3.11</span> Random forests</a></li>
  <li><a href="#how-a-random-forest-is-made" id="toc-how-a-random-forest-is-made" class="nav-link" data-scroll-target="#how-a-random-forest-is-made"><span class="header-section-number">3.12</span> How a random forest is made</a></li>
  <li><a href="#random-forest-regression" id="toc-random-forest-regression" class="nav-link" data-scroll-target="#random-forest-regression"><span class="header-section-number">3.13</span> Random forest regression</a></li>
  <li><a href="#random-forest-regression-continued" id="toc-random-forest-regression-continued" class="nav-link" data-scroll-target="#random-forest-regression-continued"><span class="header-section-number">3.14</span> Random forest regression continued</a></li>
  <li><a href="#variable-importance" id="toc-variable-importance" class="nav-link" data-scroll-target="#variable-importance"><span class="header-section-number">3.15</span> Variable importance</a></li>
  <li><a href="#classification-with-random-forrest" id="toc-classification-with-random-forrest" class="nav-link" data-scroll-target="#classification-with-random-forrest"><span class="header-section-number">3.16</span> Classification with random forrest</a></li>
  <li><a href="#random-forest-classification" id="toc-random-forest-classification" class="nav-link" data-scroll-target="#random-forest-classification"><span class="header-section-number">3.17</span> Random forest classification</a></li>
  <li><a href="#random-forest-classification-continued" id="toc-random-forest-classification-continued" class="nav-link" data-scroll-target="#random-forest-classification-continued"><span class="header-section-number">3.18</span> Random forest classification continued</a></li>
  <li><a href="#variable-importance-1" id="toc-variable-importance-1" class="nav-link" data-scroll-target="#variable-importance-1"><span class="header-section-number">3.19</span> Variable importance</a></li>
  <li><a href="#more-prediction-summary" id="toc-more-prediction-summary" class="nav-link" data-scroll-target="#more-prediction-summary"><span class="header-section-number">3.20</span> More prediction summary</a></li>
  </ul></li>
  <li><a href="#bootstrapping-to-quantify-uncertainty" id="toc-bootstrapping-to-quantify-uncertainty" class="nav-link" data-scroll-target="#bootstrapping-to-quantify-uncertainty"><span class="header-section-number">4</span> Bootstrapping to Quantify Uncertainty</a>
  <ul class="collapse">
  <li><a href="#purpose-quantify-uncertainty" id="toc-purpose-quantify-uncertainty" class="nav-link" data-scroll-target="#purpose-quantify-uncertainty"><span class="header-section-number">4.1</span> Purpose: Quantify uncertainty</a></li>
  <li><a href="#practical-example-galtons-data" id="toc-practical-example-galtons-data" class="nav-link" data-scroll-target="#practical-example-galtons-data"><span class="header-section-number">4.2</span> Practical example: Galton’s Data</a></li>
  <li><a href="#practical-example-palmer-penguins" id="toc-practical-example-palmer-penguins" class="nav-link" data-scroll-target="#practical-example-palmer-penguins"><span class="header-section-number">4.3</span> Practical example: Palmer Penguins</a></li>
  <li><a href="#bootstrapping-idea" id="toc-bootstrapping-idea" class="nav-link" data-scroll-target="#bootstrapping-idea"><span class="header-section-number">4.4</span> Bootstrapping idea</a></li>
  <li><a href="#bootstrapping-in-practice" id="toc-bootstrapping-in-practice" class="nav-link" data-scroll-target="#bootstrapping-in-practice"><span class="header-section-number">4.5</span> Bootstrapping in practice</a></li>
  <li><a href="#resamplings-galtons-data" id="toc-resamplings-galtons-data" class="nav-link" data-scroll-target="#resamplings-galtons-data"><span class="header-section-number">4.6</span> Resamplings: Galton’s Data</a></li>
  <li><a href="#bootstrap-set-galtons-data" id="toc-bootstrap-set-galtons-data" class="nav-link" data-scroll-target="#bootstrap-set-galtons-data"><span class="header-section-number">4.7</span> Bootstrap set: Galton’s Data</a></li>
  <li><a href="#bootstrap-distribution-galtons-data" id="toc-bootstrap-distribution-galtons-data" class="nav-link" data-scroll-target="#bootstrap-distribution-galtons-data"><span class="header-section-number">4.8</span> Bootstrap distribution: Galton’s Data</a></li>
  <li><a href="#quantify-uncertainty-standard-error" id="toc-quantify-uncertainty-standard-error" class="nav-link" data-scroll-target="#quantify-uncertainty-standard-error"><span class="header-section-number">4.9</span> Quantify uncertainty? Standard error</a></li>
  <li><a href="#confidence-interval" id="toc-confidence-interval" class="nav-link" data-scroll-target="#confidence-interval"><span class="header-section-number">4.10</span> Confidence interval</a></li>
  <li><a href="#confidence-interval-meaning" id="toc-confidence-interval-meaning" class="nav-link" data-scroll-target="#confidence-interval-meaning"><span class="header-section-number">4.11</span> Confidence Interval: Meaning</a></li>
  <li><a href="#ci-precision-vs.-confidence" id="toc-ci-precision-vs.-confidence" class="nav-link" data-scroll-target="#ci-precision-vs.-confidence"><span class="header-section-number">4.12</span> CI: Precision vs.&nbsp;Confidence</a></li>
  <li><a href="#bootstrap-linear-model-coefficients" id="toc-bootstrap-linear-model-coefficients" class="nav-link" data-scroll-target="#bootstrap-linear-model-coefficients"><span class="header-section-number">4.13</span> Bootstrap linear model coefficients</a></li>
  <li><a href="#bootstrap-data-frame" id="toc-bootstrap-data-frame" class="nav-link" data-scroll-target="#bootstrap-data-frame"><span class="header-section-number">4.14</span> Bootstrap data frame</a></li>
  <li><a href="#some-coefficient-distributions" id="toc-some-coefficient-distributions" class="nav-link" data-scroll-target="#some-coefficient-distributions"><span class="header-section-number">4.15</span> Some coefficient distributions</a></li>
  <li><a href="#computed-p-values-from-each-fit" id="toc-computed-p-values-from-each-fit" class="nav-link" data-scroll-target="#computed-p-values-from-each-fit"><span class="header-section-number">4.16</span> computed p-values from each fit</a></li>
  </ul></li>
  <li><a href="#bias-variance-mse-and-crowd-wisdom" id="toc-bias-variance-mse-and-crowd-wisdom" class="nav-link" data-scroll-target="#bias-variance-mse-and-crowd-wisdom"><span class="header-section-number">5</span> Bias, Variance, MSE, and Crowd Wisdom</a>
  <ul class="collapse">
  <li><a href="#galtons-data" id="toc-galtons-data" class="nav-link" data-scroll-target="#galtons-data"><span class="header-section-number">5.1</span> Galton’s data</a></li>
  <li><a href="#rmse-galtons-data" id="toc-rmse-galtons-data" class="nav-link" data-scroll-target="#rmse-galtons-data"><span class="header-section-number">5.2</span> RMSE Galton’s data</a></li>
  <li><a href="#mse-variance-and-bias-of-estimates" id="toc-mse-variance-and-bias-of-estimates" class="nav-link" data-scroll-target="#mse-variance-and-bias-of-estimates"><span class="header-section-number">5.3</span> MSE, Variance, and Bias of estimates</a></li>
  <li><a href="#testing-for-galtons-data" id="toc-testing-for-galtons-data" class="nav-link" data-scroll-target="#testing-for-galtons-data"><span class="header-section-number">5.4</span> Testing for Galton’s data</a></li>
  <li><a href="#the-diversity-prediction-theorem" id="toc-the-diversity-prediction-theorem" class="nav-link" data-scroll-target="#the-diversity-prediction-theorem"><span class="header-section-number">5.5</span> The diversity prediction theorem</a></li>
  <li><a href="#why-is-this-message-a-bit-suggestive" id="toc-why-is-this-message-a-bit-suggestive" class="nav-link" data-scroll-target="#why-is-this-message-a-bit-suggestive"><span class="header-section-number">5.6</span> Why is this message a bit suggestive?</a></li>
  <li><a href="#accuracy-for-numerical-estimate" id="toc-accuracy-for-numerical-estimate" class="nav-link" data-scroll-target="#accuracy-for-numerical-estimate"><span class="header-section-number">5.7</span> Accuracy for numerical estimate</a></li>
  <li><a href="#d-accuracy-trueness-and-precision" id="toc-d-accuracy-trueness-and-precision" class="nav-link" data-scroll-target="#d-accuracy-trueness-and-precision"><span class="header-section-number">5.8</span> 2-d Accuracy: Trueness and Precision</a></li>
  <li><a href="#what-is-a-wise-crowd" id="toc-what-is-a-wise-crowd" class="nav-link" data-scroll-target="#what-is-a-wise-crowd"><span class="header-section-number">5.9</span> What is a wise crowd?</a></li>
  <li><a href="#summary-crowd-wisdom" id="toc-summary-crowd-wisdom" class="nav-link" data-scroll-target="#summary-crowd-wisdom"><span class="header-section-number">5.10</span> Summary Crowd Wisdom</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="W11.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">W#11: Collaborative Git, More Prediction Modeling, Quantifying Uncertainty, Crowd Wisdom</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jan Lorenz </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="preliminary" class="level2" data-number="0.1">
<h2 data-number="0.1" class="anchored" data-anchor-id="preliminary"><span class="header-section-number">0.1</span> Preliminary</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.1     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.3     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ────────────────────────────────────── tidymodels 1.5.0 ──
✔ broom        1.0.13     ✔ rsample      1.3.2 
✔ dials        1.4.4      ✔ tailor       0.1.0 
✔ infer        1.1.0      ✔ tune         2.1.0 
✔ modeldata    1.5.1      ✔ workflows    1.3.0 
✔ parsnip      1.6.0      ✔ workflowsets 1.1.1 
✔ recipes      1.3.3      ✔ yardstick    1.4.0 
── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
✖ scales::discard() masks purrr::discard()
✖ dplyr::filter()   masks stats::filter()
✖ recipes::fixed()  masks stringr::fixed()
✖ dplyr::lag()      masks stats::lag()
✖ yardstick::spec() masks readr::spec()
✖ recipes::step()   masks stats::step()</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'rpart'

The following object is masked from 'package:dials':

    prune</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ranger)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vip)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'vip'

The following object is masked from 'package:utils':

    vi</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(palmerpenguins)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'palmerpenguins'

The following object is masked from 'package:modeldata':

    penguins

The following objects are masked from 'package:datasets':

    penguins, penguins_raw</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(openintro)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: airports
Loading required package: cherryblossom
Loading required package: usdata

Attaching package: 'openintro'

The following object is masked from 'package:modeldata':

    ames</code></pre>
</div>
</div>
</section>
<section id="final-project" class="level1 page-columns page-full" data-background-color="khaki" data-number="1">
<h1 data-background-color="khaki" data-number="1"><span class="header-section-number">1</span> Final Project</h1>
<section id="a-project-report-in-a-nutshell" class="level2" data-background-color="khaki" data-number="1.1">
<h2 data-background-color="khaki" data-number="1.1" class="anchored" data-anchor-id="a-project-report-in-a-nutshell"><span class="header-section-number">1.1</span> A project report in a nutshell</h2>
<ul>
<li>You pick a dataset,</li>
<li>do some interesting question-driven data analysis with it,</li>
<li>write up a well structured and nicely formatted report about the analysis, and</li>
<li>present it at the end of the semester.</li>
</ul>
</section>
<section id="six-types-of-questions" class="level2 page-columns page-full" data-background-color="khaki" data-number="1.2">
<h2 data-background-color="khaki" data-number="1.2" class="anchored" data-anchor-id="six-types-of-questions"><span class="header-section-number">1.2</span> Six types of questions</h2>
<div class="columns">
<div class="column" style="width:60%;">
<ol type="1">
<li><strong>Descriptive:</strong> summarize a characteristic of data</li>
<li><strong>Exploratory:</strong> analyze to see if there are patterns, trends, or relationships between variables (hypothesis generating)</li>
<li><strong>Inferential:</strong> analyze patterns, trends, or relationships in representative data from a population</li>
<li><strong>Predictive:</strong> make predictions for individuals or groups of individuals</li>
<li><strong>Causal:</strong> whether changing one factor will change another factor, on average, in a population</li>
<li><strong>Mechanistic:</strong> explore “how” as opposed to whether</li>
</ol>
</div><div class="column" style="width:40%;">
<p><img src="img/DataAnalysisFlowChart_LeekPeng.jpeg" class="img-fluid"></p>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="margin-aside">
<p>Leek, Jeffery T., and Roger D. Peng. 2015. “What Is the Question?” Science 347 (6228): 1314–15. <a href="https://doi.org/10.1126/science.aaa6146" class="uri">https://doi.org/10.1126/science.aaa6146</a>.</p>
</div></div></section>
<section id="what-are-good-questions" class="level2" data-background-color="khaki" data-number="1.3">
<h2 data-background-color="khaki" data-number="1.3" class="anchored" data-anchor-id="what-are-good-questions"><span class="header-section-number">1.3</span> What are good questions?</h2>
<p>A good question</p>
<ul>
<li>is not too broad (= complicated to answer)</li>
<li>is not too specific (= trivial to answer)</li>
<li>can be answered or at least approached with data</li>
<li>call for one of the different types of data analysis:
<ul>
<li>descriptive</li>
<li>exploratory</li>
<li>inferential</li>
<li>predictive</li>
<li>(causal or mechanistic – not the typical choices for a short term data analysis projects. They should not be central but may be touched.)</li>
</ul></li>
</ul>
</section>
<section id="tools-and-advice-for-questions" class="level2" data-background-color="khaki" data-number="1.4">
<h2 data-background-color="khaki" data-number="1.4" class="anchored" data-anchor-id="tools-and-advice-for-questions"><span class="header-section-number">1.4</span> Tools and advice for questions</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><span style="color:blue;"><strong>Descriptive</strong></span></p>
<div class="fragment">
<ul>
<li>What is an observation? <span style="color:red;">Answer this in any data analysis!</span></li>
<li>What are the variables?</li>
<li>Summary statistics and basic visualizations</li>
<li>Category frequencies and numerical distributions</li>
</ul>
</div>
</div><div class="column" style="width:50%;">
<p><span style="color:blue;"><strong>Exploratory</strong></span></p>
<div class="fragment">
<ul>
<li>Questions specific to the topic</li>
<li>Compute/summarize relevant variables: percentages, ratios, differences, …)</li>
<li>Scatter plots</li>
<li>Correlations</li>
<li>Cluster Analysis</li>
<li><strong>Crafted computations and visualizations for your particular questions</strong></li>
</ul>
</div>
</div>
</div>
</section>
<section id="tools-and-advice-for-questions-1" class="level2" data-background-color="khaki" data-number="1.5">
<h2 data-background-color="khaki" data-number="1.5" class="anchored" data-anchor-id="tools-and-advice-for-questions-1"><span class="header-section-number">1.5</span> Tools and advice for questions</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><span style="color:blue;"><strong>Inferential</strong></span></p>
<div class="fragment">
<ul>
<li>Describe the population the data represents</li>
<li>Can it be considered a random sample?</li>
<li>Think theoretically about variable selection and data transformations</li>
<li>Interpret coefficients of models</li>
<li>Be careful interpreting coefficients when variables are highly correlated</li>
<li>Are effects statistically significant?</li>
<li>Hypothesis test: Describe null distribution</li>
</ul>
</div>
</div><div class="column" style="width:50%;">
<p><span style="color:blue;"><strong>Predictive</strong></span></p>
<div class="fragment">
<ul>
<li>Regression or classification?</li>
<li>Do a train/test split to evaluate model performance (Optional, do crossvalidation)</li>
<li>Select sensible performance metrics for the problem (from confusion matrix or regression metrics)</li>
<li>Maybe compare different models and tune hyperparameters</li>
<li>Do feature selection and feature engineering to improve the performance!</li>
</ul>
</div>
</div>
</div>
</section>
<section id="modeling-mindsets" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="modeling-mindsets"><span class="header-section-number">1.6</span> Modeling Mindsets</h2>
<p><img src="img/ModelingMindsets_annotated.png" height="300"></p>
<p>Some methods:<br>
<strong>Linear Model:</strong> <span class="fragment" style="color:red;">Inferential</span> <span class="fragment" style="color:red;">and Predictive!</span><br>
<strong>Logistic Regression:</strong> <span class="fragment" style="color:red;">Inferential</span> <span class="fragment" style="color:red;">and Predictive!</span><br>
<strong>k-means Clustering:</strong> <span class="fragment" style="color:red;">Exploratory</span></p>
</section>
</section>
<section id="collaborative-work-git" class="level1 page-columns page-full" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Collaborative Work: Git</h1>
<p>Learning goal: First experiences with collaborative data science work with <code>git</code>.</p>
<p>Follow these steps in your project teams.</p>
<section id="step-1-git-clone-finalproject_" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="step-1-git-clone-finalproject_"><span class="header-section-number">2.1</span> Step 1: git clone <code>FinalProject_*</code></h2>
<p><strong>You are to deliver your project reports in your repository.</strong></p>
<p>All team members do the following:</p>
<ul>
<li>Find your project repository</li>
<li>Copy the URL<br>
</li>
<li>Go to Positron
<ul>
<li>New Folder from Git… &gt; Paste your URL</li>
<li>The project is created at the place you select</li>
</ul></li>
</ul>
</section>
<section id="step-2-first-team-member-commits-and-pushes" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="step-2-first-team-member-commits-and-pushes"><span class="header-section-number">2.2</span> Step 2: First Team member commits and pushes</h2>
<p><strong>One team member does the following:</strong></p>
<ul>
<li>Open the file <code>report.qmd</code></li>
<li>Write your name in the first line at <code>author</code> in the YAML</li>
<li><code>git add</code> the file <code>report.qmd</code></li>
<li><code>git commit</code> (enter “Added name” as commit message)</li>
<li><code>git push</code></li>
</ul>
</section>
<section id="step-3-other-team-members-pull" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="step-3-other-team-members-pull"><span class="header-section-number">2.3</span> Step 3: Other team members pull</h2>
<ul>
<li>Do <code>git pull</code>, or find the button “Pull” in the GRAPH section of the Source Control Tab of Positron.</li>
</ul>
<div class="columns">
<div class="column" style="width:60%;">
<p><strong>What does <code>git pull</code> do?</strong></p>
<ul>
<li><code>git pull</code> does two things: fetching new stuff and merging it with existing stuff
<ol type="1">
<li>First, it <code>git fetch</code>es the commit from the remote repository (GitHub) to the local machine</li>
<li>Then, it <code>git merge</code>s the commit with the latest commit on your local machine.</li>
</ol></li>
<li>When we are lucky merging works with no problems. (Should be the case with new files.)</li>
</ul>
</div><div class="column" style="width:40%;">
<p><img src="https://files.mastodon.social/media_attachments/files/109/303/119/338/776/592/original/662a5e803a5e6c21.png" class="img-fluid"></p>
<p>Source: <a href="https://mastodon.social/@allison_horst/109303149552034159">mastodon.social/<span class="citation" data-cites="allison_horst">@allison_horst</span></a></p>
</div>
</div>
</section>
<section id="step-4-merge-independent-changes" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="step-4-merge-independent-changes"><span class="header-section-number">2.4</span> Step 4: Merge independent changes</h2>
<p><span style="color:blue;">Git can merge changes in the same file when there are no conflicts.</span> Let’s try.</p>
<ul>
<li><strong>The second team member:</strong>
<ul>
<li>Add your name in the author section of the YAML, save the file, <code>git add</code>, <code>commit</code> and with message “Next author name” and <code>push</code>.</li>
</ul></li>
<li><strong>The third (or first) team member:</strong>
<ul>
<li>Change the title in the YAML to something meaningful and also add your name (if you are the third team member not the first again), save the file, <code>git add</code> and <code>commit</code> with message “Title changed”.</li>
<li>Try to <code>push</code>. You should receive an error. Read it carefully, often it tells you what to do. Here: Do <code>git pull</code> first. Why you can’t push? Because remotely there is a newer commit (the one your colleague just made).</li>
<li><code>Pull</code>. This should result in message about a <strong>successfull auto-merge</strong>. Check that <strong>both</strong> are there: Your line and the line of your colleague. <em>If you receive several hints instead, first read the next slide!</em></li>
</ul></li>
</ul>
</section>
<section id="git-configuration-for-divergent-branches" class="level2 page-columns page-full" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="git-configuration-for-divergent-branches"><span class="header-section-number">2.5</span> ??? <code>git</code> configuration for divergent branches</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>If you pull for the first time in a local git repository, git may complain like this:</p>
<p><img src="img/gitconfigrebase_rstudio.png" height="200"></p>
<p>Read that carefully. It advises to configure with <code>git config pull.rebase false</code> as the default version.</p>
</div><div class="column" style="width:50%;">
<p><strong>How to do the configuration?</strong></p>
<ul>
<li>Copy the line <code>git config pull.rebase false</code>.</li>
<li>Go to the TERMINAL. Paste the command (Ctrl+Shift+V) and press enter. Now you are done and <code>git pull</code> should work.</li>
</ul>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="margin-aside">
<p>What is a <em>branch</em> and what a <em>rebase</em>? These are features of git well worth to learn but not now. Learn at <a href="http://happygitwithr.com" class="uri">http://happygitwithr.com</a></p>
</div></div></section>
<section id="step-5-push-and-pull-the-other-way-round" class="level2" data-number="2.6">
<h2 data-number="2.6" class="anchored" data-anchor-id="step-5-push-and-pull-the-other-way-round"><span class="header-section-number">2.6</span> Step 5: Push and pull the other way round</h2>
<ul>
<li><strong>The third/first member:</strong>
<ul>
<li>The successful merge creates a new commit, which you can directly push.</li>
<li><code>push</code></li>
</ul></li>
<li><strong>The second team member (and all others):</strong>
<ul>
<li><code>pull</code> the changes of your colleague.</li>
</ul></li>
</ul>
<p>Practice a bit more pulling and pushing commits and check the merging.</p>
</section>
<section id="step-6-create-a-merge-conflict" class="level2" data-number="2.7">
<h2 data-number="2.7" class="anchored" data-anchor-id="step-6-create-a-merge-conflict"><span class="header-section-number">2.7</span> Step 6: Create a merge conflict</h2>
<ul>
<li>First and second team members:
<ul>
<li>Write a different sentence after “Executive Summary.” in YAML <code>abstract:</code>.</li>
<li>Both <code>git add</code> and <code>git commit</code> on their local machines.</li>
</ul></li>
<li>First member: <code>git push</code></li>
<li>Second member:
<ul>
<li><code>git pull</code>. That should result in a conflict. <em>If you receive several hints instead, first read the slide two slides before!</em></li>
<li>The conflict is visible directly in the file with markings like this</li>
</ul></li>
</ul>
<p><code>&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;</code><br>
one option of text,<br>
<code>========</code> a separator,<br>
the other option, and<br>
<code>&lt;&lt;&lt;&lt;&lt;&lt;&lt;</code>.</p>
</section>
<section id="step-7-solve-the-conflict" class="level2" data-number="2.8">
<h2 data-number="2.8" class="anchored" data-anchor-id="step-7-solve-the-conflict"><span class="header-section-number">2.8</span> Step 7: Solve the conflict</h2>
<ul>
<li>The second member
<ul>
<li>You have to solve this conflict now!</li>
<li>Solving is by editing the text</li>
<li>Decide for an option or make a new text</li>
<li>Thereby, remove the <code>&gt;&gt;&gt;&gt;&gt;</code>,<code>=====</code>,<code>&lt;&lt;&lt;&lt;&lt;&lt;</code></li>
<li>When you are done: <code>git add</code>, <code>git commit</code>, and <code>git push</code>.</li>
</ul></li>
</ul>
<p>Now you know how to solve merge conflicts. Practice a bit in your team.</p>
</section>
<section id="advice-collaborative-work-with-git" class="level2" data-number="2.9">
<h2 data-number="2.9" class="anchored" data-anchor-id="advice-collaborative-work-with-git"><span class="header-section-number">2.9</span> Advice: Collaborative work with git</h2>
<ul>
<li>First <strong>pull</strong> whenever you start a work session in a collaborative project.</li>
<li>Inform your colleagues when you pushed new commits.</li>
<li>Coordinate the work, e.g.&nbsp;discuss who works on what part and maybe when.</li>
<li>When you finish your work session, end with pushing a <em>nice</em> commit. That means. The file should preview well.</li>
<li>When you work on different parts of the file, be aware that also a successful merge can create problems. Example: Your colleague changed the data import, while you worked on graphics. Maybe after the merge the imported data is not what you need for your cell. Coordinate your data especially data import and wrangling.</li>
<li>Commit and push often. This avoids that potential merge conflicts become large.</li>
</ul>
</section>
</section>
<section id="more-prediction-modeling-cross-validation-tuning-random-forests" class="level1 page-columns page-full" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> More Prediction Modeling: Cross-Validation, Tuning, Random Forests</h1>
<section id="workflow-prediction-model" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="workflow-prediction-model"><span class="header-section-number">3.1</span> Workflow prediction model</h2>
<ol type="1">
<li>Data splitting into training and test data<br>
<code>initial_split()</code>, <code>training()</code>, <code>testing()</code> <span class="math inline">\(\to\)</span> <code>train</code> and <code>test</code> datasets</li>
<li>Recipe for preprocessing<br>
<code>recipe()</code>, specify response variable and preprocessing steps for predictors</li>
<li>Model specification<br>
E.g. <code>decision_tree()</code>, set engine <code>rpart</code>, mode <code>regression</code> or <code>classification</code></li>
<li>Workflow to combine recipe and model (still all just specifications)<br>
<code>workflow()</code> with <code>add_recipe()</code>, <code>add_model()</code> creates a workflow object</li>
<li>Fit the model with training data using the workflow (finally the computation happens!) <code>fit()</code> with workflow and <code>train</code> data</li>
<li>Predict response variable for rows of the test data<br>
<code>predict()</code> with fitted workflow and <code>test</code> data</li>
<li>Evaluate performance using the orignal variable (ground truth) in test data<br>
<code>metrics()</code> by specifying <code>truth</code> and <code>estimate</code> columns</li>
</ol>
</section>
<section id="decision-tree" class="level2 page-columns page-full" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="decision-tree"><span class="header-section-number">3.2</span> Decision Tree</h2>
<div class="cell" data-output-location="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12345</span>) <span class="co"># Test with other seeds to see how the Train-Test-Split changes results!</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Train-Test-Split</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>peng_split <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(<span class="fu">na.omit</span>(penguins), <span class="at">prop =</span> <span class="fl">0.8</span>, <span class="at">strata =</span> sex)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>peng_train <span class="ot">&lt;-</span> <span class="fu">training</span>(peng_split)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>peng_test <span class="ot">&lt;-</span> <span class="fu">testing</span>(peng_split)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="cn">NULL</span>) <span class="co"># Reset random. See that the decision tree algorithm is deterministic! Test it!</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Preprocessing-Recipe</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>peng_recipe <span class="ot">&lt;-</span> <span class="fu">recipe</span>(body_mass_g <span class="sc">~</span> ., <span class="at">data =</span> peng_train) <span class="sc">|&gt;</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_rm</span>(year)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Model</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>peng_regtree <span class="ot">&lt;-</span> <span class="fu">decision_tree</span>() <span class="sc">|&gt;</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"rpart"</span>) <span class="sc">|&gt;</span></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">"regression"</span>)</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. Workflow</span></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>peng_regtree_wf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">|&gt;</span></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(peng_recipe) <span class="sc">|&gt;</span></span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(peng_regtree)</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a><span class="co"># 5. Fit</span></span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>peng_regtree_fit <span class="ot">&lt;-</span> peng_regtree_wf <span class="sc">|&gt;</span> </span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(<span class="at">data =</span> peng_train)</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a><span class="co"># 6. Predict with test data</span></span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>peng_regtree_pred <span class="ot">&lt;-</span> peng_regtree_fit <span class="sc">|&gt;</span></span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(peng_test)</span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a><span class="co"># 7. Evaluate performance</span></span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a>peng_regtree_pred <span class="sc">|&gt;</span></span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">metrics</span>(<span class="at">truth =</span> body_mass_g, <span class="at">estimate =</span> .pred)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 rmse    standard     350.   
2 rsq     standard       0.811
3 mae     standard     284.   </code></pre>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="margin-aside">
<p>New: <code>augment()</code> adds the predictions as a new column <code>.pred</code> to the <code>peng_test</code> data-frame. Before we did the same manually with <code>predict()</code> and <code>bind_cols()</code>.</p>
</div></div></section>
<section id="decision-tree-hyper-parameters" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="decision-tree-hyper-parameters"><span class="header-section-number">3.3</span> Decision Tree: Hyper-Parameters</h2>
<div class="cell" data-output-location="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check hyperparameters used</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Cost complexity:"</span>, <span class="fu">extract_fit_engine</span>(peng_regtree_fit)<span class="sc">$</span>control<span class="sc">$</span>cp, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Min split:"</span>, <span class="fu">extract_fit_engine</span>(peng_regtree_fit)<span class="sc">$</span>control<span class="sc">$</span>minsplit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cost complexity: 0.01 
 Min split: 20</code></pre>
</div>
</div>
<ul>
<li>Cost complexity (<code>cp</code>): Controls pruning of the tree. Higher values result in smaller trees.</li>
<li>Minimum split (<code>minsplit</code>): Minimum number of observations in a node to be allowed to split further. Higher values result in smaller trees.</li>
<li>Note: Terminology in <code>tidymodels</code> and original <code>rpart</code> differ. <code>tidymodels</code> tries to unifying terminology across models. Thus, <code>cp</code> is called <code>cost_complexity</code> and <code>minsplit</code> is called <code>min_n</code>.</li>
</ul>
<p>. . .</p>
<ul>
<li><span class="green"><strong>Is the decision tree a deterministic algorithm?</strong></span><br>
<span class="fragment">Yes, given the same training data and hyperparameters, it always results in the same tree.</span></li>
</ul>
<p>. . .</p>
<p>However, the Test-Train-Split is and the performance measures would be different for each new split!</p>
</section>
<section id="how-reliable-are-performance-metrics" class="level2 smaller" data-number="3.4">
<h2 class="smaller anchored" data-number="3.4" data-anchor-id="how-reliable-are-performance-metrics"><span class="header-section-number">3.4</span> How reliable are performance metrics?</h2>
<ul>
<li>Model performance changes with the random selection of the training data. How can we then reliably compare models?</li>
</ul>
<p>. . .</p>
<p>A solution: <span class="green"><strong>Cross-validation</strong></span></p>
<p>. . .</p>
<p>More specifically, <span class="green"><strong><span class="math inline">\(v\)</span>-fold cross-validation</strong></span>:</p>
<ul>
<li>Shuffle your data and make a partition with <span class="math inline">\(v\)</span> parts
<ul>
<li>Recall from set theory: A <strong>partition</strong> is a division of a set into mutually disjoint parts which union cover the whole set. Here applied to observations (rows) in a data frame.</li>
</ul></li>
<li>Use 1 part for validation, and the remaining <span class="math inline">\(v-1\)</span> parts for training</li>
<li>Repeat <span class="math inline">\(v\)</span> times</li>
</ul>
</section>
<section id="cross-validation" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="cross-validation"><span class="header-section-number">3.5</span> Cross-validation</h2>
<p><img src="img/cross-validation.png" class="img-fluid"></p>
</section>
<section id="cross-validation-1" class="level2 page-columns page-full" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="cross-validation-1"><span class="header-section-number">3.6</span> Cross-validation</h2>
<p>Cross-validation replacing the Train-Test-Split in the workflow:</p>
<div class="cell" data-output-location="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>) <span class="co"># Test with other seeds to see how the Train-Test-Split changes results!</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. 5-fold Cross validation</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>peng_folds <span class="ot">&lt;-</span> <span class="fu">vfold_cv</span>(<span class="fu">na.omit</span>(penguins), <span class="at">v =</span> <span class="dv">5</span>, <span class="at">strata =</span> sex)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="cn">NULL</span>) <span class="co"># Reset random. See that the decision tree algorithm is deterministic! Test it!</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Preprocessing-Recipe: Same as before</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Model: Same as before</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. Workflow: Same as before</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="co"># 5. Fit: We use peng_regtree_wf and use fit_resamples() to fit for all folds</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>peng_regtree_fit <span class="ot">&lt;-</span> peng_regtree_wf <span class="sc">|&gt;</span> </span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit_resamples</span>(<span class="at">resamples =</span> peng_folds)</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a><span class="co"># 6./7. (Predict) and evaluate performance for all folds</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>peng_regtree_fit <span class="sc">|&gt;</span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">collect_metrics</span>(<span class="at">summarize =</span> <span class="cn">FALSE</span>, <span class="at">type =</span> <span class="st">"wide"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 4
  .config         id     rmse   rsq
  &lt;chr&gt;           &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt;
1 pre0_mod0_post0 Fold1  251. 0.893
2 pre0_mod0_post0 Fold2  361. 0.817
3 pre0_mod0_post0 Fold3  319. 0.841
4 pre0_mod0_post0 Fold4  316. 0.905
5 pre0_mod0_post0 Fold5  324. 0.806</code></pre>
</div>
</div>
<p>. . .</p>
<div class="columns">
<div class="column">
<p>Interpretation:</p>
<ul>
<li>Cross-validation shows variation</li>
<li>The original fit was worse than average</li>
</ul>
</div><div class="column">
<p>For comparision: Original split</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 rmse    standard     350.   
2 rsq     standard       0.811
3 mae     standard     284.   </code></pre>
</div>
</div>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="margin-aside">
<p>Besides <code>vfold_cv()</code> the only new function are <code>fit_resamples()</code> and <code>collect_metrics()</code>.</p>
</div></div></section>
<section id="tuning" class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="tuning"><span class="header-section-number">3.7</span> Tuning</h2>
<div class="cell" data-output-location="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 1.a. Train-Test-Split (same as before)</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co"># 1.b. CREATE CROSS-VALIDATION FOLDS for TRAINING data</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>peng_folds <span class="ot">&lt;-</span> <span class="fu">vfold_cv</span>(peng_train, <span class="at">v =</span> <span class="dv">5</span>, <span class="at">repeats =</span> <span class="dv">5</span>, <span class="at">strata =</span> sex)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Preprocessing-Recipe (same)</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Model WITH TUNING (modified)</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>peng_regtree <span class="ot">&lt;-</span> <span class="fu">decision_tree</span>(</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">cost_complexity =</span> <span class="fu">tune</span>(),</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">min_n =</span> <span class="fu">tune</span>()</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"rpart"</span>) <span class="sc">|&gt;</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">"regression"</span>)</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a><span class="co"># 4.a. Workflow (same but with new model)</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>peng_wf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">|&gt;</span></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(peng_recipe) <span class="sc">|&gt;</span></span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(peng_regtree)</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a><span class="co"># 4.b. TUNE WITH CROSS-VALIDATION</span></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>peng_tune_results <span class="ot">&lt;-</span> peng_wf <span class="sc">|&gt;</span></span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tune_grid</span>(</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">resamples =</span> peng_folds,</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">grid =</span> <span class="fu">expand_grid</span>(</span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>        <span class="at">cost_complexity =</span> <span class="fu">c</span>(<span class="fl">0.05</span>, <span class="fl">0.02</span>, <span class="fl">0.01</span>, <span class="fl">0.005</span>),</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a>        <span class="at">min_n =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">40</span>)</span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>    ), </span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">metrics =</span> <span class="fu">metric_set</span>(rmse)</span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a><span class="co"># 4.c. EXAMINE TUNING RESULTS</span></span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a>peng_tune_results <span class="sc">|&gt;</span></span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">collect_metrics</span>(<span class="at">summarize =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> <span class="fu">select</span>(<span class="sc">-</span>.config, <span class="sc">-</span>.estimator)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 16 × 6
   cost_complexity min_n .metric  mean     n std_err
             &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt;
 1           0.005     2 rmse     315.    25    6.78
 2           0.005    10 rmse     316.    25    7.30
 3           0.005    20 rmse     322.    25    7.84
 4           0.005    40 rmse     324.    25    8.09
 5           0.01      2 rmse     313.    25    7.13
 6           0.01     10 rmse     313.    25    7.13
 7           0.01     20 rmse     314.    25    8.02
 8           0.01     40 rmse     314.    25    8.15
 9           0.02      2 rmse     312.    25    7.22
10           0.02     10 rmse     312.    25    7.22
11           0.02     20 rmse     313.    25    8.10
12           0.02     40 rmse     314.    25    8.57
13           0.05      2 rmse     317.    25   10.9 
14           0.05     10 rmse     317.    25   10.9 
15           0.05     20 rmse     317.    25   10.9 
16           0.05     40 rmse     317.    25   10.9 </code></pre>
</div>
</div>
<p><code>collect_metrics(summarize = TRUE)</code> averages performance across folds and repeats!<br>
In total there are 400 fits (16 parameter combinations <span class="math inline">\(\times\)</span> 5 folds <span class="math inline">\(\times\)</span> 5 repeats).</p>
</section>
<section id="tuning-continued" class="level2" data-number="3.8">
<h2 data-number="3.8" class="anchored" data-anchor-id="tuning-continued"><span class="header-section-number">3.8</span> Tuning continued</h2>
<p>Visualization for evalution</p>
<div class="cell" data-output-location="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 4.d. VISUALIZE TUNING RESULTS</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(peng_tune_results) <span class="sc">+</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">18</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W11_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="tuning-continued-1" class="level2" data-number="3.9">
<h2 data-number="3.9" class="anchored" data-anchor-id="tuning-continued-1"><span class="header-section-number">3.9</span> Tuning continued</h2>
<p>Selection of best parameters</p>
<div class="cell" data-output-location="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 4.e. SEE BEST PARAMETERS AND SELECT BEST</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>best_params <span class="ot">&lt;-</span> <span class="fu">select_best</span>(peng_tune_results, <span class="at">metric =</span> <span class="st">"rmse"</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">show_best</span>(peng_tune_results, <span class="at">metric =</span> <span class="st">"rmse"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>.estimator, <span class="sc">-</span>.config)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 6
  cost_complexity min_n .metric  mean     n std_err
            &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt;
1            0.02     2 rmse     312.    25    7.22
2            0.02    10 rmse     312.    25    7.22
3            0.01     2 rmse     313.    25    7.13
4            0.01    10 rmse     313.    25    7.13
5            0.02    20 rmse     313.    25    8.10</code></pre>
</div>
</div>
<p>Best parameters: <code>min_n</code> = 2, <code>cost_complexity</code> = 0.02</p>
</section>
<section id="fit-with-tune-parameters" class="level2" data-number="3.10">
<h2 data-number="3.10" class="anchored" data-anchor-id="fit-with-tune-parameters"><span class="header-section-number">3.10</span> Fit with tune parameters</h2>
<div class="cell" data-output-location="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 5. Fit: FINALIZE AND FIT WITH BEST PARAMETERS and fit</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>peng_regtree_fit <span class="ot">&lt;-</span> peng_wf <span class="sc">|&gt;</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">finalize_workflow</span>(best_params) <span class="sc">|&gt;</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(<span class="at">data =</span> peng_train)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 6./7. Predict and Evaluatue with test data (as before)</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>peng_regtree_fit <span class="sc">|&gt;</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(peng_test) <span class="sc">|&gt;</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">metrics</span>(<span class="at">truth =</span> body_mass_g, <span class="at">estimate =</span> .pred)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 rmse    standard     350.   
2 rsq     standard       0.811
3 mae     standard     284.   </code></pre>
</div>
</div>
<ul>
<li>Although, best parameters differ from default, performance is the same.</li>
<li>This can happen, especially when the model is simple and the dataset is small.</li>
</ul>
<p>. . .</p>
<p>How can we improve the performance with the idea of trees?<br>
<span class="green fragment"><strong>Create several trees and aggregate them in a random forest!</strong></span></p>
</section>
<section id="random-forests" class="level2 page-columns page-full" data-number="3.11">
<h2 data-number="3.11" class="anchored" data-anchor-id="random-forests"><span class="header-section-number">3.11</span> Random forests</h2>
<p><img src="https://upload.wikimedia.org/wikipedia/commons/4/4e/Random_forest_explain.png" class="img-fluid"></p>

<div class="no-row-height column-margin column-container"><div class="margin-aside">
<p>Source: <a href="https://de.wikipedia.org/wiki/Random_Forest" class="uri">https://de.wikipedia.org/wiki/Random_Forest</a></p>
</div></div></section>
<section id="how-a-random-forest-is-made" class="level2" data-number="3.12">
<h2 data-number="3.12" class="anchored" data-anchor-id="how-a-random-forest-is-made"><span class="header-section-number">3.12</span> How a random forest is made</h2>
<ul>
<li>Build many decision trees independently (default: 500 trees), each trained on the full dataset<br>
In each tree do the following at each decision node:
<ul>
<li>Randomly select <code>mtry</code> features from all available features (e.g., 2 out of 6, rule of thumb: square root of the number of features)</li>
<li>Find the best split only among those randomly selected features.<br>
The randomness in variable selection at each split ensures trees are different from each other, this shall reduce overfitting.</li>
</ul></li>
<li>Make predictions by
<ul>
<li>averaging predictions across all trees (regression) or</li>
<li>majority vote (classification)</li>
</ul></li>
</ul>
</section>
<section id="random-forest-regression" class="level2" data-number="3.13">
<h2 data-number="3.13" class="anchored" data-anchor-id="random-forest-regression"><span class="header-section-number">3.13</span> Random forest regression</h2>
<div class="cell" data-output-location="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Train-Test-Split</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Preprocessing-Recipe</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Model</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>peng_regforest <span class="ot">&lt;-</span> <span class="fu">rand_forest</span>() <span class="sc">|&gt;</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"ranger"</span>, <span class="at">importance =</span> <span class="st">"impurity"</span>) <span class="sc">|&gt;</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">"regression"</span>)</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. Workflow</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>peng_regforest_fit <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">|&gt;</span></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(peng_recipe) <span class="sc">|&gt;</span></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(peng_regforest) <span class="sc">|&gt;</span></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a><span class="co"># 5. Fit</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(<span class="at">data =</span> peng_train)</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>peng_regforest_fit</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>══ Workflow [trained] ══════════════════════════════════════════════════════════
Preprocessor: Recipe
Model: rand_forest()

── Preprocessor ────────────────────────────────────────────────────────────────
1 Recipe Step

• step_rm()

── Model ───────────────────────────────────────────────────────────────────────
Ranger result

Call:
 ranger::ranger(x = maybe_data_frame(x), y = y, importance = ~"impurity",      num.threads = 1, verbose = FALSE, seed = sample.int(10^5,          1)) 

Type:                             Regression 
Number of trees:                  500 
Sample size:                      266 
Number of independent variables:  6 
Mtry:                             2 
Target node size:                 5 
Variable importance mode:         impurity 
Splitrule:                        variance 
OOB prediction error (MSE):       82877.84 
R squared (OOB):                  0.8734915 </code></pre>
</div>
</div>
<p>With <code>set_engine("ranger", importance = "impurity")</code> we specify the method of specification for the computation of <span class="green"><strong>variable importance</strong></span>.</p>
</section>
<section id="random-forest-regression-continued" class="level2" data-number="3.14">
<h2 data-number="3.14" class="anchored" data-anchor-id="random-forest-regression-continued"><span class="header-section-number">3.14</span> Random forest regression continued</h2>
<div class="cell" data-output-location="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 6./7. Predict and Evaluatue with test data (as before)</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>peng_regforest_fit <span class="sc">|&gt;</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(peng_test) <span class="sc">|&gt;</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">metrics</span>(<span class="at">truth =</span> body_mass_g, <span class="at">estimate =</span> .pred)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 rmse    standard     323.   
2 rsq     standard       0.836
3 mae     standard     265.   </code></pre>
</div>
</div>
<ul>
<li>Random forest often outperform decision tree and linear models. (Here, only a little bit.)</li>
<li>However, they have no natural visualization and are less interpretable.<br>
They have thousands of parameters with all these trees!</li>
</ul>
</section>
<section id="variable-importance" class="level2" data-number="3.15">
<h2 data-number="3.15" class="anchored" data-anchor-id="variable-importance"><span class="header-section-number">3.15</span> Variable importance</h2>
<p><strong>Variable importance</strong> identify features that matter for good predicitions.</p>
<div class="cell" data-output-location="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 6./7. Predict and Evaluatue with test data (as before)</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Variable importance</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">extract_fit_engine</span>(peng_regforest_fit) <span class="sc">|&gt;</span> </span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">vip</span>() <span class="sc">+</span> <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">18</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W11_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>The computation of variable importance is typically consider a step of <span class="green"><strong>post-processing</strong></span> of complex models like random forests because it is computed after the model is fitted.</li>
<li>In contrast, <strong>pre-processing</strong> happens before fitting the model.</li>
</ul>
<p>All details about exact definition and different methods to compute variable importance are skipped here.</p>
</section>
<section id="classification-with-random-forrest" class="level2" data-number="3.16">
<h2 data-number="3.16" class="anchored" data-anchor-id="classification-with-random-forrest"><span class="header-section-number">3.16</span> Classification with random forrest</h2>
<p>First the spam prediction decision tree</p>
<div class="cell" data-output-location="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12345</span>) <span class="co"># Just to fix the presentation, test without when doing yourself!</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Train-Test-Split</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>email_split <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(email, <span class="at">prop =</span> <span class="fl">0.7</span>, <span class="at">strata =</span> spam)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>email_train <span class="ot">&lt;-</span> <span class="fu">training</span>(email_split)</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>email_test <span class="ot">&lt;-</span> <span class="fu">testing</span>(email_split)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Preprocessing-Recipe</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>email_recipe <span class="ot">&lt;-</span> <span class="fu">recipe</span>(spam <span class="sc">~</span> ., <span class="at">data =</span> email) <span class="sc">|&gt;</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_rm</span>(from, sent_email, viagra) <span class="sc">|&gt;</span> <span class="co"># Remove some variables (see former lectures)</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_date</span>(time, <span class="at">features =</span> <span class="fu">c</span>(<span class="st">"dow"</span>, <span class="st">"month"</span>)) <span class="sc">|&gt;</span> <span class="co"># Make day-of-week and month features ...</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_rm</span>(time) <span class="sc">|&gt;</span> <span class="co"># ... and remove the date-time itself</span></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_zv</span>(<span class="fu">all_predictors</span>()) <span class="co"># remove predictors with zero variance</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Model</span></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>email_classtree <span class="ot">&lt;-</span> <span class="fu">decision_tree</span>() <span class="sc">|&gt;</span></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"rpart"</span>) <span class="sc">|&gt;</span></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">"classification"</span>)</span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. Workflow</span></span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>email_classtree_wf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">|&gt;</span></span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(email_recipe) <span class="sc">|&gt;</span></span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(email_classtree)</span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a><span class="co"># 5. Fit</span></span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a>email_classtree_fit <span class="ot">&lt;-</span> email_classtree_wf <span class="sc">|&gt;</span> </span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(<span class="at">data =</span> email_train)</span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a><span class="co"># 6./7. Predict with test data and evaluate performance</span></span>
<span id="cb32-24"><a href="#cb32-24" aria-hidden="true" tabindex="-1"></a>class_metrics <span class="ot">&lt;-</span> <span class="fu">metric_set</span>(accuracy, sensitivity, specificity)</span>
<span id="cb32-25"><a href="#cb32-25" aria-hidden="true" tabindex="-1"></a>email_classtree_fit <span class="sc">|&gt;</span></span>
<span id="cb32-26"><a href="#cb32-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(email_test) <span class="sc">|&gt;</span></span>
<span id="cb32-27"><a href="#cb32-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">class_metrics</span>(<span class="at">truth =</span> spam, <span class="at">estimate =</span> .pred_class, <span class="at">event_level =</span> <span class="st">"second"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  .metric     .estimator .estimate
  &lt;chr&gt;       &lt;chr&gt;          &lt;dbl&gt;
1 accuracy    binary         0.910
2 sensitivity binary         0.244
3 specificity binary         0.988</code></pre>
</div>
</div>
</section>
<section id="random-forest-classification" class="level2" data-number="3.17">
<h2 data-number="3.17" class="anchored" data-anchor-id="random-forest-classification"><span class="header-section-number">3.17</span> Random forest classification</h2>
<div class="cell" data-output-location="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Train-Test-Split</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>email_split <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(<span class="fu">na.omit</span>(email), <span class="at">prop =</span> <span class="fl">0.8</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>email_train <span class="ot">&lt;-</span> <span class="fu">training</span>(email_split)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>email_test <span class="ot">&lt;-</span> <span class="fu">testing</span>(email_split)</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Preprocessing-Recipe</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>email_recipe <span class="ot">&lt;-</span> <span class="fu">recipe</span>(spam <span class="sc">~</span> ., <span class="at">data =</span> email) <span class="sc">|&gt;</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_rm</span>(from, sent_email, viagra) <span class="sc">|&gt;</span> <span class="co"># Remove some variables (see former lectures)</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_date</span>(time, <span class="at">features =</span> <span class="fu">c</span>(<span class="st">"dow"</span>, <span class="st">"month"</span>)) <span class="sc">|&gt;</span> <span class="co"># Make day-of-week and month features ...</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_rm</span>(time) <span class="sc">|&gt;</span> <span class="co"># ... and remove the date-time itself</span></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_zv</span>(<span class="fu">all_predictors</span>()) <span class="co"># remove predictors with zero variance</span></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Model</span></span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>email_forest <span class="ot">&lt;-</span> <span class="fu">rand_forest</span>() <span class="sc">|&gt;</span></span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"ranger"</span>, <span class="at">importance =</span> <span class="st">"impurity"</span>) <span class="sc">|&gt;</span></span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">"classification"</span>)</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. Workflow</span></span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>email_forest_fit <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">|&gt;</span></span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(email_recipe) <span class="sc">|&gt;</span></span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(email_forest) <span class="sc">|&gt;</span></span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 5. Fit</span></span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(<span class="at">data =</span> email_train)</span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a>email_forest_fit <span class="co"># Look at the fit object</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>══ Workflow [trained] ══════════════════════════════════════════════════════════
Preprocessor: Recipe
Model: rand_forest()

── Preprocessor ────────────────────────────────────────────────────────────────
4 Recipe Steps

• step_rm()
• step_date()
• step_rm()
• step_zv()

── Model ───────────────────────────────────────────────────────────────────────
Ranger result

Call:
 ranger::ranger(x = maybe_data_frame(x), y = y, importance = ~"impurity",      num.threads = 1, verbose = FALSE, seed = sample.int(10^5,          1), probability = TRUE) 

Type:                             Probability estimation 
Number of trees:                  500 
Sample size:                      3136 
Number of independent variables:  18 
Mtry:                             4 
Target node size:                 10 
Variable importance mode:         impurity 
Splitrule:                        gini 
OOB prediction error (Brier s.):  0.04985914 </code></pre>
</div>
</div>
</section>
<section id="random-forest-classification-continued" class="level2" data-number="3.18">
<h2 data-number="3.18" class="anchored" data-anchor-id="random-forest-classification-continued"><span class="header-section-number">3.18</span> Random forest classification continued</h2>
<div class="cell" data-output-location="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 6./7. Predict with test data and evaluate performance</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>email_forest_fit <span class="sc">|&gt;</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(email_test) <span class="sc">|&gt;</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">class_metrics</span>(<span class="at">truth =</span> spam, <span class="at">estimate =</span> .pred_class, <span class="at">event_level =</span> <span class="st">"second"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  .metric     .estimator .estimate
  &lt;chr&gt;       &lt;chr&gt;          &lt;dbl&gt;
1 accuracy    binary         0.935
2 sensitivity binary         0.378
3 specificity binary         0.993</code></pre>
</div>
</div>
<p>In particular specificity (true negative rate) is better than for the decision tree!</p>
<p>. . .</p>
<p>How does prediction work for classification with random forests? How do we aggregate the classification of all the trees in the forrest? (For regression we were averaging.)<br>
<span class="green fragment"><strong>Majority vote across all trees!</strong></span></p>
</section>
<section id="variable-importance-1" class="level2" data-number="3.19">
<h2 data-number="3.19" class="anchored" data-anchor-id="variable-importance-1"><span class="header-section-number">3.19</span> Variable importance</h2>
<div class="cell" data-output-location="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Variable importance</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">extract_fit_engine</span>(email_classtree_fit) <span class="sc">|&gt;</span> </span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">vip</span>() <span class="sc">+</span> <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">18</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W11_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-output-location="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Variable importance</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">extract_fit_engine</span>(email_forest_fit) <span class="sc">|&gt;</span> </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">vip</span>() <span class="sc">+</span> <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">18</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W11_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="more-prediction-summary" class="level2" data-number="3.20">
<h2 data-number="3.20" class="anchored" data-anchor-id="more-prediction-summary"><span class="header-section-number">3.20</span> More prediction summary</h2>
<div class="incremental">
<ul class="incremental">
<li>A <strong>decision tree</strong> is <em>deterministic</em>. However, results change with different train-test-splits.</li>
<li><strong>Cross-validation</strong> helps to assess model performance more reliably.</li>
<li><strong>Tuning hyperparameters</strong> can improve model performance, but often defaults are good.
<ul class="incremental">
<li>It is all about quantifying when <em>overfitting</em> kicks in and <em>out-of-sample performance</em> degrades.</li>
</ul></li>
<li><strong>Random forests</strong> take the idea of decision trees further by creating many trees and aggregating their predictions. They are not deterministic but <em>stochastic</em> even with the same training data.</li>
<li>Why are random forrests better than individual trees?
<ul class="incremental">
<li>By limiting choices at each split to a random subset of features, we prevent any single strong predictor from dominating all trees, creating a diverse “forest” of models that collectively perform better than any individual tree.</li>
</ul></li>
</ul>
</div>
</section>
</section>
<section id="bootstrapping-to-quantify-uncertainty" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Bootstrapping to Quantify Uncertainty</h1>
<section id="purpose-quantify-uncertainty" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="purpose-quantify-uncertainty"><span class="header-section-number">4.1</span> Purpose: Quantify uncertainty</h2>
<ul>
<li><strong>Uncertainty</strong> is a central concern in <span class="red"><strong>inferential data analysis</strong></span>.</li>
<li>We want to <strong>estimate</strong> a <strong>parameter</strong> of a <span class="red"><strong>population</strong></span> from a <span class="red"><strong>sample</strong></span>.</li>
</ul>
<p>. . .</p>
<p>Central inferential assumption:</p>
<ul>
<li>Our data is a <strong>random sample</strong> from the <strong>population</strong> we are interested in.
<ul>
<li>No <strong>selection biases</strong>.</li>
</ul></li>
</ul>
<p>Examples:</p>
<ul>
<li>We want to know <strong>average height</strong> of <strong>all people</strong> but we only have a sample of people.</li>
<li>We want know the <strong>mean estimate</strong> of all possible participants of the ox meat weigh guessing competition from the <strong>sample ballots</strong> of participants we have.</li>
<li>We want to learn something about penguins from the data of the penguins in <code>palmerpenguins::penguins</code></li>
</ul>
</section>
<section id="practical-example-galtons-data" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="practical-example-galtons-data"><span class="header-section-number">4.2</span> Practical example: Galton’s Data</h2>
<p>Competition: Guess the weight of the meat of an Ox? (Galton, 1907)</p>
<p><em>What is the mean of all possible participants <span class="math inline">\(\mu\)</span>?</em></p>
<p>. . .</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>galton <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"galton.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 787 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (2): Estimate, id

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>galton <span class="sc">|&gt;</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(Estimate)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W11_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The (arithmetic) mean of the 787 estimates is <span class="math inline">\(\hat\mu =\)</span> 1196.71.</p>
<p><em>How sure can we be that <span class="math inline">\(\hat\mu\)</span> is close to <span class="math inline">\(\mu\)</span> and how can we quantify?</em><a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
</section>
<section id="practical-example-palmer-penguins" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="practical-example-palmer-penguins"><span class="header-section-number">4.3</span> Practical example: Palmer Penguins</h2>
<p>A linear model for body mass of penguins: <span class="math inline">\(y_i = \beta_0 + \beta_1 x_i + \dots + \beta_m x_m  + \varepsilon_i\)</span>.</p>
<p>. . .</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>peng_workflow <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">|&gt;</span> <span class="fu">add_recipe</span>(<span class="fu">recipe</span>(body_mass_g <span class="sc">~</span> ., <span class="at">data =</span> penguins) <span class="sc">|&gt;</span> <span class="fu">step_rm</span>(year)) <span class="sc">|&gt;</span> </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(<span class="fu">linear_reg</span>() <span class="sc">|&gt;</span> <span class="fu">set_engine</span>(<span class="st">"lm"</span>))</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>peng_fit <span class="ot">&lt;-</span> peng_workflow <span class="sc">|&gt;</span> <span class="fu">fit</span>(<span class="at">data =</span> penguins)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>peng_fit <span class="sc">|&gt;</span> <span class="fu">tidy</span>() <span class="sc">|&gt;</span> <span class="fu">mutate_if</span>(is.numeric, round, <span class="dv">7</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 5
  term              estimate std.error statistic   p.value
  &lt;chr&gt;                &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)        -1500.     576.      -2.61  0.00961  
2 speciesChinstrap    -260.      88.6     -2.94  0.00352  
3 speciesGentoo        988.     137.       7.20  0        
4 islandDream          -13.1     58.5     -0.224 0.823    
5 islandTorgersen      -48.1     60.9     -0.789 0.431    
6 bill_length_mm        18.2      7.14     2.55  0.0113   
7 bill_depth_mm         67.6     19.8      3.41  0.000734 
8 flipper_length_mm     16.2      2.94     5.52  0.0000001
9 sexmale              387.      48.1      8.04  0        </code></pre>
</div>
</div>
<p>. . .</p>
<p>The column <code>estimate</code> shows the coefficients <span class="math inline">\(\hat\beta_0, \hat\beta_1, \dots, \hat\beta_m\)</span> of the linear model for the variables named in <code>term</code></p>
<p><em>How sure can we be that the <span class="math inline">\(\hat\beta\)</span>’s are close to the <span class="math inline">\(\beta\)</span>’s we are interested in?</em><a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
</section>
<section id="bootstrapping-idea" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="bootstrapping-idea"><span class="header-section-number">4.4</span> Bootstrapping<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> idea</h2>
<ol type="1">
<li>Take a <strong>bootstrap sample</strong>: a random sample taken with replacement from the original sample with the same size.</li>
<li>Calculate the <em>statistics</em> for the bootstrap sample.</li>
<li>Repeat steps 1. and 2. many times to create a <strong>bootstrap distribution</strong> - a distribution of bootstrap statistics</li>
<li>Use the bootstrap distribution to quantify the uncertainty.</li>
</ol>
<p>What is the statistic in the Galton example? <span class="fragment">The mean</span><br>
What are the statistics in the penguins example? <span class="fragment">The coefficients</span></p>
</section>
<section id="bootstrapping-in-practice" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="bootstrapping-in-practice"><span class="header-section-number">4.5</span> Bootstrapping in practice</h2>
<ul>
<li>You can do the bootstrapping procedure in various ways (including programming in base R or python).</li>
<li>We will use convenient functions from <code>rsample</code> form the <code>tidymodels</code> packages.</li>
</ul>
</section>
<section id="resamplings-galtons-data" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="resamplings-galtons-data"><span class="header-section-number">4.6</span> Resamplings: Galton’s Data</h2>
<div class="columns">
<div class="column" style="width:35%;">
<p>The function <code>sample</code> selects <code>size</code> random elements from a vector <code>x</code> with or without <code>replace</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">224</span>)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(galton<span class="sc">$</span>Estimate, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1177 1232 1242</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(galton<span class="sc">$</span>Estimate, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1270 1440 1232</code></pre>
</div>
</div>
<p>For tibbles we can use <code>slice_sample</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>galton <span class="sc">|&gt;</span> <span class="fu">slice_sample</span>(<span class="at">n =</span> <span class="dv">3</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  Estimate    id
     &lt;dbl&gt; &lt;dbl&gt;
1     1189   320
2     1203   367
3     1181   278</code></pre>
</div>
</div>
</div><div class="column" style="width:35%;">
<div class="fragment">
<p>A <strong>bootstrap sample</strong> is with replace and of the same size as the original sample:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(galton)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 787</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>galton <span class="sc">|&gt;</span> <span class="fu">slice_sample</span>(<span class="at">n =</span> <span class="dv">787</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 787 × 2
   Estimate    id
      &lt;dbl&gt; &lt;dbl&gt;
 1     1347   774
 2     1221   489
 3     1112    85
 4     1320   766
 5     1266   697
 6     1145   149
 7     1271   711
 8     1215   442
 9     1238   596
10     1163   198
# ℹ 777 more rows</code></pre>
</div>
</div>
</div>
</div><div class="column" style="width:30%;">
<div class="fragment">
<p>Compute some <code>mean</code>s of bootstrapping samples manually:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>galton <span class="sc">|&gt;</span> <span class="fu">slice_sample</span>(<span class="at">n =</span> <span class="dv">787</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> </span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">summarize</span>(<span class="fu">mean</span>(Estimate))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  `mean(Estimate)`
             &lt;dbl&gt;
1            1194.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>galton <span class="sc">|&gt;</span> <span class="fu">slice_sample</span>(<span class="at">n =</span> <span class="dv">787</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> </span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">summarize</span>(<span class="fu">mean</span>(Estimate))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  `mean(Estimate)`
             &lt;dbl&gt;
1            1197.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>galton <span class="sc">|&gt;</span> <span class="fu">slice_sample</span>(<span class="at">n =</span> <span class="dv">787</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> </span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">summarize</span>(<span class="fu">mean</span>(Estimate))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  `mean(Estimate)`
             &lt;dbl&gt;
1            1193.</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="bootstrap-set-galtons-data" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="bootstrap-set-galtons-data"><span class="header-section-number">4.7</span> Bootstrap set: Galton’s Data</h2>
<p>The function <code>bootstraps</code> from <code>rsample</code> does this type of bootstrapping for us.</p>
<div class="columns">
<div class="column" style="width:50%;">
<p>1,000 resamples:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>boots_galton <span class="ot">&lt;-</span> galton <span class="sc">|&gt;</span> <span class="fu">bootstraps</span>(<span class="at">times =</span> <span class="dv">1000</span>)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>boots_galton <span class="sc">|&gt;</span> <span class="fu">head</span>(<span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  splits            id           
  &lt;list&gt;            &lt;chr&gt;        
1 &lt;split [787/295]&gt; Bootstrap0001
2 &lt;split [787/293]&gt; Bootstrap0002
3 &lt;split [787/296]&gt; Bootstrap0003
4 &lt;split [787/303]&gt; Bootstrap0004
5 &lt;split [787/283]&gt; Bootstrap0005</code></pre>
</div>
</div>
<p>The column <code>splits</code> contains split objects.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>boots_galton<span class="sc">$</span>splits[[<span class="dv">1</span>]]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;Analysis/Assess/Total&gt;
&lt;787/295/787&gt;</code></pre>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="fragment">
<p>From each split we can extract the bootstrapped resample with <code>analysis</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>boots_galton<span class="sc">$</span>splits[[<span class="dv">1</span>]] <span class="sc">|&gt;</span> <span class="fu">analysis</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 787 × 2
   Estimate    id
      &lt;dbl&gt; &lt;dbl&gt;
 1     1160   192
 2     1260   678
 3     1147   153
 4     1221   484
 5     1204   373
 6     1165   211
 7     1112    85
 8     1415   780
 9     1081    43
10     1168   220
# ℹ 777 more rows</code></pre>
</div>
</div>
<p>Note: An <code>assessment</code> set contains the observations not selected randomly in the resample. We ignore it here.</p>
</div>
</div>
</div>
</section>
<section id="bootstrap-distribution-galtons-data" class="level2" data-number="4.8">
<h2 data-number="4.8" class="anchored" data-anchor-id="bootstrap-distribution-galtons-data"><span class="header-section-number">4.8</span> Bootstrap distribution: Galton’s Data</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>We iterate with a <code>map</code> function<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> over the splits and extract the analysis set and calculate the mean.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>boots_galton_mean <span class="ot">&lt;-</span> boots_galton <span class="sc">|&gt;</span> </span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>   <span class="at">mean =</span> <span class="fu">map_dbl</span>(splits, </span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>                  \(x) <span class="fu">analysis</span>(x)<span class="sc">$</span>Estimate <span class="sc">|&gt;</span> <span class="fu">mean</span>()))</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>boots_galton_mean <span class="sc">|&gt;</span> <span class="fu">head</span>(<span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 3
  splits            id             mean
  &lt;list&gt;            &lt;chr&gt;         &lt;dbl&gt;
1 &lt;split [787/295]&gt; Bootstrap0001 1194.
2 &lt;split [787/293]&gt; Bootstrap0002 1196.
3 &lt;split [787/296]&gt; Bootstrap0003 1199.
4 &lt;split [787/303]&gt; Bootstrap0004 1196.
5 &lt;split [787/283]&gt; Bootstrap0005 1194.</code></pre>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="fragment">
<p>Plot the bootstrap distribution of the mean.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>boots_galton_mean <span class="sc">|&gt;</span> </span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> mean)) <span class="sc">+</span> <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a> <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">24</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W11_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div class="fragment">
<p>Compare distribution of estimates</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>galton <span class="sc">|&gt;</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(Estimate)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">24</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W11_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="quantify-uncertainty-standard-error" class="level2" data-number="4.9">
<h2 data-number="4.9" class="anchored" data-anchor-id="quantify-uncertainty-standard-error"><span class="header-section-number">4.9</span> Quantify uncertainty? Standard error</h2>
<p>Compute the standard deviation of the bootstrap distribution.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(boots_galton_mean<span class="sc">$</span>mean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.732243</code></pre>
</div>
</div>
<p>. . .</p>
<p>The standard deviation of the bootstrap distribution is called the <strong>standard error</strong> of the statistic.</p>
<p><span style="color:red;">Do not confuse standard error (of a statistic) and standard deviation (of a variable).</span></p>
<p>The <strong>standard error of the mean</strong> can also be estimated directly from the original sample <span class="math inline">\(x\)</span> as <span class="math inline">\(\frac{\text{sd}(x)}{\sqrt{n}}\)</span> where <span class="math inline">\(n\)</span> is the sample size.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(galton<span class="sc">$</span>Estimate) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">nrow</span>(galton))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.623085</code></pre>
</div>
</div>
<p>. . .</p>
<p><span style="color:blue;">Insight:</span> The standard error decreases with sample size! However, it decreases only with the square root of the sample size.</p>
<p><span style="color:blue;">Question:</span> You want to shrink the standard error by half. How much larger does the sample size need to be? <span class="fragment">4 times</span></p>
</section>
<section id="confidence-interval" class="level2" data-number="4.10">
<h2 data-number="4.10" class="anchored" data-anchor-id="confidence-interval"><span class="header-section-number">4.10</span> Confidence interval</h2>
<p>Another way to quantify uncertainty is to compute a <strong>confidence interval</strong> (CI) for a certain <strong>confidence level</strong>:<br>
The true value of the statistic is expected to lie with the CI with certain probability (the confidence level).</p>
<p>. . .</p>
<div class="columns">
<div class="column" style="width:30%;">
<p>Compute the 95% confidence interval of the bootstrap distribution with <code>quantile</code>-functions:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>boots_galton_mean <span class="sc">|&gt;</span> </span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">lower =</span> <span class="fu">quantile</span>(mean, <span class="fl">0.025</span>),</span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">upper =</span> <span class="fu">quantile</span>(mean, <span class="fl">0.975</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  lower upper
  &lt;dbl&gt; &lt;dbl&gt;
1 1191. 1202.</code></pre>
</div>
</div>
</div><div class="column" style="width:60%;">
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>boots_galton_mean <span class="sc">|&gt;</span> </span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> mean)) <span class="sc">+</span> <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a> <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">quantile</span>(boots_galton_mean<span class="sc">$</span>mean, <span class="fl">0.025</span>), <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a> <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">quantile</span>(boots_galton_mean<span class="sc">$</span>mean, <span class="fl">0.975</span>), <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a> <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="dv">1197</span>, <span class="at">y =</span> <span class="dv">10</span>, <span class="at">label =</span> <span class="st">"95% of estimates"</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">size =</span> <span class="fu">unit</span>(<span class="dv">12</span>, <span class="st">"pt"</span>)) <span class="sc">+</span></span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a> <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">24</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W11_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="confidence-interval-meaning" class="level2" data-number="4.11">
<h2 data-number="4.11" class="anchored" data-anchor-id="confidence-interval-meaning"><span class="header-section-number">4.11</span> Confidence Interval: Meaning</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>boots_galton_mean <span class="sc">|&gt;</span> </span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">lower =</span> <span class="fu">quantile</span>(mean, <span class="fl">0.025</span>),</span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">upper =</span> <span class="fu">quantile</span>(mean, <span class="fl">0.975</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  lower upper
  &lt;dbl&gt; &lt;dbl&gt;
1 1191. 1202.</code></pre>
</div>
</div>
<p>What is the correct interpretation?</p>
<ol type="1">
<li>95% of the estimates in this sample lie between 1191 and 1202.</li>
<li>We are 95% confident that the mean estimate of all potential participants is between 1191 and 1202.</li>
<li>We are 95% confident that the mean estimate of this sample is between 1191 and 1202.</li>
</ol>
<p>. . .</p>
<p>Correct: 2.<br>
1. The confidence is about a statistic (here, population mean) not about sample values!<br>
3. We know the mean of the sample precisely!<br>
The confidence interval assesses where 95% of the values are when we sample anew.</p>
</section>
<section id="ci-precision-vs.-confidence" class="level2" data-number="4.12">
<h2 data-number="4.12" class="anchored" data-anchor-id="ci-precision-vs.-confidence"><span class="header-section-number">4.12</span> CI: Precision vs.&nbsp;Confidence</h2>
<ul>
<li>Can’t we increase the confidence level to 99% to get a more precise estimate with a more narrow confidence interval?</li>
</ul>
<p>. . .</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>boots_galton_mean <span class="sc">|&gt;</span> </span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">lower =</span> <span class="fu">quantile</span>(mean, <span class="fl">0.005</span>),</span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">upper =</span> <span class="fu">quantile</span>(mean, <span class="fl">0.995</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  lower upper
  &lt;dbl&gt; &lt;dbl&gt;
1 1190. 1204.</code></pre>
</div>
</div>
<p><span style="color:red;">No, it is the other way round:</span> The smaller and more precise the confidence interval, the lower must the confidence level be.</p>
</section>
<section id="bootstrap-linear-model-coefficients" class="level2" data-number="4.13">
<h2 data-number="4.13" class="anchored" data-anchor-id="bootstrap-linear-model-coefficients"><span class="header-section-number">4.13</span> Bootstrap linear model coefficients</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>peng_workflow <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">|&gt;</span> <span class="fu">add_recipe</span>(<span class="fu">recipe</span>(body_mass_g <span class="sc">~</span> ., <span class="at">data =</span> penguins) <span class="sc">|&gt;</span> <span class="fu">step_rm</span>(year)) <span class="sc">|&gt;</span> </span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(<span class="fu">linear_reg</span>() <span class="sc">|&gt;</span> <span class="fu">set_engine</span>(<span class="st">"lm"</span>))</span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>peng_fit <span class="ot">&lt;-</span> peng_workflow <span class="sc">|&gt;</span> <span class="fu">fit</span>(<span class="at">data =</span> penguins)</span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a>peng_fit <span class="sc">|&gt;</span> <span class="fu">tidy</span>() <span class="sc">|&gt;</span> <span class="fu">mutate_if</span>(is.numeric, round, <span class="dv">7</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 5
  term              estimate std.error statistic   p.value
  &lt;chr&gt;                &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)        -1500.     576.      -2.61  0.00961  
2 speciesChinstrap    -260.      88.6     -2.94  0.00352  
3 speciesGentoo        988.     137.       7.20  0        
4 islandDream          -13.1     58.5     -0.224 0.823    
5 islandTorgersen      -48.1     60.9     -0.789 0.431    
6 bill_length_mm        18.2      7.14     2.55  0.0113   
7 bill_depth_mm         67.6     19.8      3.41  0.000734 
8 flipper_length_mm     16.2      2.94     5.52  0.0000001
9 sexmale              387.      48.1      8.04  0        </code></pre>
</div>
</div>
<p>. . .</p>
<p>Let us now bootstrap whole models instead of just mean values!</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A function to fit a model to a bootstrap sample and tidy the coefficients</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>fit_split <span class="ot">&lt;-</span> <span class="cf">function</span>(split) peng_workflow <span class="sc">|&gt;</span> <span class="fu">fit</span>(<span class="at">data =</span> <span class="fu">analysis</span>(split)) <span class="sc">|&gt;</span> <span class="fu">tidy</span>() </span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Make 1000 bootstrap samples and fit a model to each</span></span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>boots_peng <span class="ot">&lt;-</span> <span class="fu">bootstraps</span>(penguins, <span class="at">times =</span> <span class="dv">1000</span>) <span class="sc">|&gt;</span> </span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">coefs =</span> <span class="fu">map</span>(splits, fit_split))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="bootstrap-data-frame" class="level2 scrollable" data-number="4.14">
<h2 class="scrollable anchored" data-number="4.14" data-anchor-id="bootstrap-data-frame"><span class="header-section-number">4.14</span> Bootstrap data frame</h2>
<p>Now we have a column <code>coefs</code> with a list of data frames, each containing the fitted coefficients.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>boots_peng</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># Bootstrap sampling 
# A tibble: 1,000 × 3
   splits            id            coefs           
   &lt;list&gt;            &lt;chr&gt;         &lt;list&gt;          
 1 &lt;split [344/125]&gt; Bootstrap0001 &lt;tibble [9 × 5]&gt;
 2 &lt;split [344/131]&gt; Bootstrap0002 &lt;tibble [9 × 5]&gt;
 3 &lt;split [344/123]&gt; Bootstrap0003 &lt;tibble [9 × 5]&gt;
 4 &lt;split [344/116]&gt; Bootstrap0004 &lt;tibble [9 × 5]&gt;
 5 &lt;split [344/130]&gt; Bootstrap0005 &lt;tibble [9 × 5]&gt;
 6 &lt;split [344/126]&gt; Bootstrap0006 &lt;tibble [9 × 5]&gt;
 7 &lt;split [344/126]&gt; Bootstrap0007 &lt;tibble [9 × 5]&gt;
 8 &lt;split [344/129]&gt; Bootstrap0008 &lt;tibble [9 × 5]&gt;
 9 &lt;split [344/129]&gt; Bootstrap0009 &lt;tibble [9 × 5]&gt;
10 &lt;split [344/129]&gt; Bootstrap0010 &lt;tibble [9 × 5]&gt;
# ℹ 990 more rows</code></pre>
</div>
</div>
<p>We can <code>unnest</code> the list column to make a much longer but unnested data frame:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>boots_peng <span class="sc">|&gt;</span> <span class="fu">unnest</span>(coefs)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9,000 × 7
   splits            id            term    estimate std.error statistic  p.value
   &lt;list&gt;            &lt;chr&gt;         &lt;chr&gt;      &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
 1 &lt;split [344/125]&gt; Bootstrap0001 (Inter… -1972.      630.     -3.13   1.91e- 3
 2 &lt;split [344/125]&gt; Bootstrap0001 specie…  -294.       94.9    -3.10   2.09e- 3
 3 &lt;split [344/125]&gt; Bootstrap0001 specie…   958.      137.      6.97   1.84e-11
 4 &lt;split [344/125]&gt; Bootstrap0001 island…    -1.14     57.7    -0.0197 9.84e- 1
 5 &lt;split [344/125]&gt; Bootstrap0001 island…   -71.9      61.8    -1.16   2.45e- 1
 6 &lt;split [344/125]&gt; Bootstrap0001 bill_l…    22.3       8.00    2.78   5.68e- 3
 7 &lt;split [344/125]&gt; Bootstrap0001 bill_d…    80.1      20.6     3.88   1.26e- 4
 8 &lt;split [344/125]&gt; Bootstrap0001 flippe…    16.8       3.00    5.61   4.40e- 8
 9 &lt;split [344/125]&gt; Bootstrap0001 sexmale   353.       51.2     6.89   2.94e-11
10 &lt;split [344/131]&gt; Bootstrap0002 (Inter… -1945.      585.     -3.33   9.82e- 4
# ℹ 8,990 more rows</code></pre>
</div>
</div>
</section>
<section id="some-coefficient-distributions" class="level2" data-number="4.15">
<h2 data-number="4.15" class="anchored" data-anchor-id="some-coefficient-distributions"><span class="header-section-number">4.15</span> Some coefficient distributions</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>g1 <span class="ot">&lt;-</span> boots_peng <span class="sc">|&gt;</span> <span class="fu">unnest</span>(coefs) <span class="sc">|&gt;</span> <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"islandDream"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> estimate)) <span class="sc">+</span> <span class="fu">geom_histogram</span>() <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">"coefficients islandDream"</span>) <span class="sc">+</span></span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"gray"</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">24</span>)</span>
<span id="cb91-4"><a href="#cb91-4" aria-hidden="true" tabindex="-1"></a>g2 <span class="ot">&lt;-</span> boots_peng <span class="sc">|&gt;</span> <span class="fu">unnest</span>(coefs) <span class="sc">|&gt;</span> <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"bill_length_mm"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb91-5"><a href="#cb91-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> estimate)) <span class="sc">+</span> <span class="fu">geom_histogram</span>() <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">"coefficients bill_length_mm"</span>) <span class="sc">+</span></span>
<span id="cb91-6"><a href="#cb91-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"gray"</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">24</span>)</span>
<span id="cb91-7"><a href="#cb91-7" aria-hidden="true" tabindex="-1"></a>g3 <span class="ot">&lt;-</span> boots_peng <span class="sc">|&gt;</span> <span class="fu">unnest</span>(coefs) <span class="sc">|&gt;</span> <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"flipper_length_mm"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb91-8"><a href="#cb91-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> estimate)) <span class="sc">+</span> <span class="fu">geom_histogram</span>() <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">"coefficients flipper_length_mm"</span>) <span class="sc">+</span></span>
<span id="cb91-9"><a href="#cb91-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"gray"</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">24</span>)</span>
<span id="cb91-10"><a href="#cb91-10" aria-hidden="true" tabindex="-1"></a>g1 <span class="sc">+</span> g2 <span class="sc">+</span> g3</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value `binwidth`.
`stat_bin()` using `bins = 30`. Pick better value `binwidth`.
`stat_bin()` using `bins = 30`. Pick better value `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W11_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid figure-img" width="1728"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>We could derive <em>bootstrapped p-values</em> from these distributions.</li>
</ul>
</section>
<section id="computed-p-values-from-each-fit" class="level2" data-number="4.16">
<h2 data-number="4.16" class="anchored" data-anchor-id="computed-p-values-from-each-fit"><span class="header-section-number">4.16</span> computed p-values from each fit</h2>
<ul>
<li>Each bootstrap fit also delivers computed p-values for each coefficient.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>g1 <span class="ot">&lt;-</span> boots_peng <span class="sc">|&gt;</span> <span class="fu">unnest</span>(coefs) <span class="sc">|&gt;</span> <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"islandDream"</span>) <span class="sc">|&gt;</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> p.value)) <span class="sc">+</span> <span class="fu">geom_histogram</span>() <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">"coefficients islandDream"</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">24</span>)</span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>g2 <span class="ot">&lt;-</span> boots_peng <span class="sc">|&gt;</span> <span class="fu">unnest</span>(coefs) <span class="sc">|&gt;</span> <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"bill_length_mm"</span>) <span class="sc">|&gt;</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> p.value)) <span class="sc">+</span> <span class="fu">geom_histogram</span>() <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">"coefficients bill_length_mm"</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">24</span>)</span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>g3 <span class="ot">&lt;-</span> boots_peng <span class="sc">|&gt;</span> <span class="fu">unnest</span>(coefs) <span class="sc">|&gt;</span> <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"flipper_length_mm"</span>) <span class="sc">|&gt;</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> p.value)) <span class="sc">+</span> <span class="fu">geom_histogram</span>() <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">"coefficients flipper_length_mm"</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">24</span>)</span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a>g1 <span class="sc">+</span> g2 <span class="sc">+</span> g3</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value `binwidth`.
`stat_bin()` using `bins = 30`. Pick better value `binwidth`.
`stat_bin()` using `bins = 30`. Pick better value `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W11_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid figure-img" width="1728"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>computed p-values in resamples vary widely (see <code>islandDream</code>) when <em>bootstrapped p-values</em> show insignificance.</li>
</ul>
</section>
</section>
<section id="bias-variance-mse-and-crowd-wisdom" class="level1 page-columns page-full" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Bias, Variance, MSE, and Crowd Wisdom</h1>
<section id="galtons-data" class="level2 page-columns page-full" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="galtons-data"><span class="header-section-number">5.1</span> Galton’s data</h2>
<p><em>What is the weight of the meat of this ox?</em></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a>galton <span class="sc">|&gt;</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(Estimate)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>) <span class="sc">+</span> <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">1198</span>, <span class="at">color =</span> <span class="st">"green"</span>) <span class="sc">+</span> </span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(galton<span class="sc">$</span>Estimate), <span class="at">color =</span> <span class="st">"red"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W11_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>787 estimates, <span style="color:green;">true value</span> 1198, <span style="color:red;">mean</span> 1196.7</p>

<div class="no-row-height column-margin column-container"><div class="margin-aside">
<p>We focus on the arithmetic mean as aggregation function for the wisdom of the crowd here.</p>
</div></div></section>
<section id="rmse-galtons-data" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="rmse-galtons-data"><span class="header-section-number">5.2</span> RMSE Galton’s data</h2>
<p>Describe the estimation game as a predictive model:</p>
<ul>
<li>All <em>estimates</em> are made to predict the same value: the truth.
<ul>
<li>In contrast to the regression model, the estimate come from people and not from a regression formula.</li>
</ul></li>
<li>The <em>truth</em> is the same for all.
<ul>
<li>In contrast to the regression model, the truth is one value and not a value for each prediction</li>
</ul></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a>rmse_galton <span class="ot">&lt;-</span> galton <span class="sc">|&gt;</span> </span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">mutate</span>(<span class="at">true_value =</span> <span class="dv">1198</span>) <span class="sc">|&gt;</span></span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a> <span class="fu">rmse</span>(<span class="at">truth =</span> true_value, Estimate)</span>
<span id="cb96-4"><a href="#cb96-4" aria-hidden="true" tabindex="-1"></a>rmse_galton</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 rmse    standard        73.6</code></pre>
</div>
</div>
<!-- ## Regression vs. crowd estimation -->
<!-- The linear regression and the crowd estimation problems are similar but not identical! -->
<!-- |Variable      | Linear Regression Model                       | Crowd estimation -->
<!-- |--------------|-----------------------------------------------|-------------------------------------------- -->
<!-- | $y_i$        | Data point of response variable               | True value, uniform for all estimators $y_i = y$ -->
<!-- | $\hat{y}_i$  | Predicted value $\hat{y}_i=b_0+b_1+x_1+\dots$ | Estimate of one estimator -->
<!-- | $\bar{y}$    | Mean of response variable                     | Mean of estimates  -->
</section>
<section id="mse-variance-and-bias-of-estimates" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="mse-variance-and-bias-of-estimates"><span class="header-section-number">5.3</span> MSE, Variance, and Bias of estimates</h2>
<p>In a crowd estimation, <span class="math inline">\(n\)</span> estimators delivered the estimates <span class="math inline">\(\hat{y}_1,\dots,\hat{y}_n\)</span>. Let us look at the following measures</p>
<ul>
<li><p><span class="math inline">\(\bar{y} = \frac{1}{n}\sum_{i = 1}^n \hat{y}_i^2\)</span> is the mean estimate, it is the aggregated estimate of the crowd</p></li>
<li><p><span class="math inline">\(\text{MSE} = \text{RMSE}^2 = \frac{1}{n}\sum_{i = 1}^n (\text{truth} - \hat{y}_i)^2\)</span></p></li>
<li><p><span class="math inline">\(\text{Variance} = \frac{1}{n}\sum_{i = 1}^n (\hat{y}_i - \bar{y})^2\)</span></p></li>
<li><p><span class="math inline">\(\text{Bias-squared} = (\bar{y} - \text{truth})^2\)</span> which is the square difference between truth and mean estimate.</p></li>
</ul>
<p>There is a mathematical relation (a math exercise to check):</p>
<p><span class="math display">\[\text{MSE} = \text{Bias-squared} + \text{Variance}\]</span></p>
</section>
<section id="testing-for-galtons-data" class="level2 page-columns page-full" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="testing-for-galtons-data"><span class="header-section-number">5.4</span> Testing for Galton’s data</h2>
<p><span class="math display">\[\text{MSE} = \text{Bias-squared} + \text{Variance}\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a>MSE <span class="ot">&lt;-</span> (rmse_galton<span class="sc">$</span>.estimate)<span class="sc">^</span><span class="dv">2</span> </span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a>MSE</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5409.795</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>Variance <span class="ot">&lt;-</span> <span class="fu">var</span>(galton<span class="sc">$</span>Estimate)<span class="sc">*</span>(<span class="fu">nrow</span>(galton)<span class="sc">-</span><span class="dv">1</span>)<span class="sc">/</span><span class="fu">nrow</span>(galton)</span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Note, we had to correct for the divisor (n-1) in the classical statistical definition</span></span>
<span id="cb100-3"><a href="#cb100-3" aria-hidden="true" tabindex="-1"></a><span class="co"># to get the sample variance instead of the estimate for the population variance</span></span>
<span id="cb100-4"><a href="#cb100-4" aria-hidden="true" tabindex="-1"></a>Variance</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5408.132</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>Bias_squared <span class="ot">&lt;-</span> (<span class="fu">mean</span>(galton<span class="sc">$</span>Estimate) <span class="sc">-</span> <span class="dv">1198</span>)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a>Bias_squared</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.663346</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a>Bias_squared <span class="sc">+</span> Variance</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5409.795</code></pre>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="margin-aside">
<p>Such nice mathematical properties are probably one reason why these squared measures are so popular.</p>
</div></div></section>
<section id="the-diversity-prediction-theorem" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="the-diversity-prediction-theorem"><span class="header-section-number">5.5</span> The diversity prediction theorem<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></h2>
<ul>
<li><em>MSE</em> is a measure for the average <strong>individuals error</strong></li>
<li><em>Bias-squared</em> is a measure for the <strong>collective error</strong></li>
<li><em>Variance</em> is a measure for the <strong>diversity</strong> of estimates around the mean estimate</li>
</ul>
<p>The mathematical relation <span class="math display">\[\text{MSE} = \text{Bias-squared} + \text{Variance}\]</span> can be formulated as</p>
<p><strong>Collective error = Individual error - Diversity</strong></p>
<p>Interpretation: <em>The higher the diversity the lower the collective error!</em></p>
</section>
<section id="why-is-this-message-a-bit-suggestive" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="why-is-this-message-a-bit-suggestive"><span class="header-section-number">5.6</span> Why is this message a bit suggestive?</h2>
<p>The mathematical relation <span class="math display">\[\text{MSE} = \text{Bias-squared} + \text{Variance}\]</span> can be formulated as</p>
<p><strong>Collective error = Individual error - Diversity</strong></p>
<p>Interpretation: <em>The higher the diversity the lower the collective error!</em></p>
<p>. . .</p>
<ul>
<li><span class="math inline">\(\text{MSE}\)</span> and <span class="math inline">\(\text{Variance}\)</span> are not independent!</li>
<li>Activities to increase diversity (Variance) typically also increase the average individual error (MSE).</li>
<li>For example, if we just add more random estimates with same mean but wild variance to our sample we increase both and do not gain any decrease of the collective error.</li>
</ul>
</section>
<section id="accuracy-for-numerical-estimate" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="accuracy-for-numerical-estimate"><span class="header-section-number">5.7</span> Accuracy for numerical estimate</h2>
<ul>
<li>For binary classifiers <strong>accuracy</strong> has a simple definition: Fraction of correct classifications.
<ul>
<li>It can be further informed by other more specific measures taken from the confusion matrix (sensitivity, specificity)</li>
</ul></li>
</ul>
<p>How about numerical estimators?<br>
For example outcomes of estimation games, or linear regression models?</p>
<p>. . .</p>
<ul>
<li>Accuracy is for example measured by (R)MSE</li>
<li><span class="math inline">\(\text{MSE} = \text{Bias-squared} + \text{Variance}\)</span> shows us that we can make a<br>
<strong>bias-variance decomposition</strong></li>
<li>That means some part of the error is a systematic (the bias) and another part due to random variation (the variance).</li>
</ul>
</section>
<section id="d-accuracy-trueness-and-precision" class="level2" data-number="5.8">
<h2 data-number="5.8" class="anchored" data-anchor-id="d-accuracy-trueness-and-precision"><span class="header-section-number">5.8</span> 2-d Accuracy: Trueness and Precision</h2>
<p>According to ISO 5725-1 Standard: <em>Accuracy (trueness and precision) of measurement methods and results - Part 1: General principles and definitions.</em> there are two dimension of accuracy of numerical measurement.</p>
<p><img src="https://upload.wikimedia.org/wikipedia/commons/9/92/Accuracy_%28trueness_and_precision%29.svg" class="img-fluid"> <img src="img/accuracy_trueness_precision.png" height="300"></p>
</section>
<section id="what-is-a-wise-crowd" class="level2" data-number="5.9">
<h2 data-number="5.9" class="anchored" data-anchor-id="what-is-a-wise-crowd"><span class="header-section-number">5.9</span> What is a wise crowd?</h2>
<p>Assume the dots are estimates. <strong>Which is a wise crowd?</strong></p>
<p><img src="img/accuracy_trueness_precision.png" height="300"></p>
<p>. . .</p>
<ul>
<li>Of course, high trueness and high precision! But, …</li>
<li>Focusing on the <strong>crowd</strong> being wise instead of its <strong>individuals</strong>: High trueness, low precision.</li>
</ul>
</section>
<section id="summary-crowd-wisdom" class="level2" data-number="5.10">
<h2 data-number="5.10" class="anchored" data-anchor-id="summary-crowd-wisdom"><span class="header-section-number">5.10</span> Summary Crowd Wisdom</h2>
<ul>
<li>The <strong>wisdom of the crowd</strong> relies on aggregating diverse estimates.</li>
<li>More generally as these simple guessing games, <strong>crowd wisdom</strong> is this idea:<br>
<em>Many problems can be solved better by aggregating the answers of many individuals than by relying on a single expert.</em></li>
<li>The <strong>random forest</strong> method of statistical learning is built on this idea:<br>
<em>Instead of relying on on heavyily fine tuned decision tree, we create a forrest of many partly randomly generated trees and aggregate their predictions.</em>
<ul>
<li>It turns out that such forest typically produce predictions that <em>generalize</em> better to new data.</li>
</ul></li>
<li>The <strong>bias-variance decomposition</strong> helps to understand different sources of errors. It is used to understand error in predicion models (not shown here).
<ul>
<li>In an underfitted model, the error stems mostly from variance</li>
<li>In an overfitted model, the error stems mostly from bias (with respect to the training data</li>
</ul></li>
</ul>


</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>We already assume that we have an unbiased sample of all possible participants!<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>We already assume that we have an unbiased sample of all penguins!<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>The name comes from the saying “pull oneself up by one’s bootstrap”. It refers to the somehow <em>magical</em> idea that we can use our small sample to <em>mimic</em> the whole population.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Here we use <code>map_dbl</code> which iterates over the list of splits and reports the values as a vector of doubles (numbers), the default of <code>map</code> would be to report also a list.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>These are computed based on theoretical assumptions with the help of t-tests and t-distributions.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Notion from: Page, S. E. (2007). The Difference: How the Power of Diversity Creates Better Groups, Firms, Schools, and Societies. Princeton University Press.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>